"""
  ______ .______   .______   .______    __  .__   __.  _______  
 /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
|  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
|  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
|  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 

This file is generated by cppbind on 06/15/2022-07:22.
Please do not change it manually.
"""
from __future__ import annotations

from typing import *

import examples.optionals.optionals as pybind_optionals_pygen
import examples_lib.enums.color_pygen as enums_color_pygen
import examples_lib.enums.logging_pygen as enums_logging_pygen
import examples_lib.getters.person_pygen as getters_person_pygen
import examples_lib.simple.project_pygen as simple_project_pygen
import examples_lib.simple.root_pygen as simple_root_pygen
import examples_lib.simple.task.task_pygen as simple_task_task_pygen
from examples_lib.cppbind.cppbind_metaclass_pygen import *
from examples_lib.cppbind.cppbind_utils_pygen import *


class Optionals(metaclass=CppBindMetaclass):
    """
    Documentation generated from: `cxx/optionals/optionals.hpp#L25
    <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L25>`_
    """
    
    @bind
    def __init__(self, task: simple_task_task_pygen.PyTask = None, i: int = 1, r: simple_root_pygen.Root = None):
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L176
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L176>`_
        """
        pass
    
    @bind
    def optional_ptr_with_nullptr_default(self, task: Optional[simple_task_task_pygen.PyTask] = None) -> Optional[simple_task_task_pygen.PyTask]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L35
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L35>`_
        """
        pass

    @bind
    def optional_ptr_with_null_default(self, task: Optional[simple_task_task_pygen.PyTask] = None) -> Optional[simple_task_task_pygen.PyTask]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L46
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L46>`_
        """
        pass

    @bind
    def optional_int_with_default(self, value: int = 5) -> int:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L55
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L55>`_
        """
        pass

    @bind
    def optional_long_with_default(self, value: int = 7) -> int:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L64
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L64>`_
        """
        pass

    @bind
    def optional_double_with_default(self, value: float = 9.0) -> float:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L73
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L73>`_
        """
        pass

    @bind
    def optional_float_with_default(self, value: float = 11.0) -> float:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L82
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L82>`_
        """
        pass

    @bind
    def optional_bool_with_default(self, value: bool = True) -> bool:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L91
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L91>`_
        """
        pass

    @bind
    def optional_string_with_default(self, optional_str: str = "abc") -> str:
        """
        @param[in] optional_str string with default value
        Documentation generated from: `cxx/optionals/optionals.hpp#L101
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L101>`_
        """
        pass

    @bind
    def optional_char_with_default(self, symbol: str = ',') -> str:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L110
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L110>`_
        """
        pass

    @bind
    def optional_unsigned_char_with_default(self, num: int = 100) -> int:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L119
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L119>`_
        """
        pass

    @bind
    def optional_char_pointer_with_default(self, optional_str: str = "def") -> str:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L128
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L128>`_
        """
        pass

    @bind
    def optional_enum_with_default(self, c: enums_color_pygen.Color = enums_color_pygen.Color.Red) -> enums_color_pygen.Color:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L137
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L137>`_
        """
        pass

    @bind
    def optional_enum_with_default_and_changed_names(self, level: enums_logging_pygen.LogLevel = enums_logging_pygen.LogLevel.WARNING) -> enums_logging_pygen.LogLevel:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L146
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L146>`_
        """
        pass

    @bind
    def single_complex_default_value(self, task: simple_task_task_pygen.PyTask = None) -> simple_task_task_pygen.PyTask:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L158
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L158>`_
        """
        pass

    @bind
    def multiple_mixed_default_values(self, task: simple_task_task_pygen.PyTask = None, i: int = 1, r: simple_root_pygen.Root = None) -> str:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L167
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L167>`_
        """
        pass

    @bind
    def optional_enum_with_default_and_field_prefix(self, c: enums_color_pygen.ColorShade = enums_color_pygen.ColorShade.ShadeLight) -> enums_color_pygen.ColorShade:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L187
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L187>`_
        """
        pass

    @bind
    def optional_enum_with_internal_default(self, c: enums_color_pygen.ColorShade) -> enums_color_pygen.ColorShade:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L196
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L196>`_
        """
        pass

    @bind
    def optional_string_view_with_default(self, optional_str: str = "abc") -> str:
        """
        @param[in] optional_str string with default value
        Documentation generated from: `cxx/optionals/optionals.hpp#L206
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L206>`_
        """
        pass

    @bind
    def optional_f_d_ptr_with_nullptr_default(self, project: Optional[simple_project_pygen.Project] = None) -> Optional[simple_project_pygen.Project]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L217
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L217>`_
        """
        pass

    @bind
    def optional_shared_ptr_with_nullptr_default(self, person: Optional[getters_person_pygen.Person] = None) -> Optional[getters_person_pygen.Person]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L227
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L227>`_
        """
        pass

    @bind
    def __repr__(self) -> str:
        """
        CppBind generated __repr__ method returning underlying C++ object type and id.
        """
        pass
