/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 06/17/2021-10:23.
 * Please do not change it manually.
 */

#ifndef simple_task_task_hpp
#define simple_task_task_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindPyTask(py::module& m);

#endif