/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 02/03/2022-13:55.
 * Please do not change it manually.
 */

#ifndef _C_json_WRAPPER_
#define _C_json_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_JsonExamples(IEGenCObject cself, bool owner);

    IEGenCObject create_JsonExamples(IEGenCObject* _Nonnull err);
    void _func_JsonExamples_setJson(IEGenCObject cself, char * _Nullable  j, IEGenCObject* _Nonnull err);
    char * _Nullable _func_JsonExamples_getJson(IEGenCObject cself, IEGenCObject* _Nonnull err);
    char * _Nullable _func_JsonExamples_getSimpleJsonExample(IEGenCObject cself, IEGenCObject* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_json_WRAPPER_ */
