# Copyright (c) 2022 PicsArt, Inc.
# All rights reserved. Use of this source code is governed by a
# MIT-style license that can be found in the LICENSE file.

utils: |
  {%- macro get_overloading_postfix(vars) -%}
  {%-   if cxx.is_overloaded -%}
  {%-     if vars.overloading_postfix is not none -%}
            {{vars.overloading_postfix}}
  {%-     elif overloading_index and overloading_index > 0 -%}
            {{overloading_index|string}}
  {%-     endif -%}
  {%-   endif -%}
  {%- endmacro -%}
  {%- macro gen_override_keyword(cxx, exclude_interface=false) -%}
  {%-   if cxx.kind_name == 'method' -%}
  {%-     if vars.is_overridden is not none -%}
  {%-       if vars.is_overridden -%}
              {{'override '}}
  {%-       endif -%}
  {%-     else -%}
  {%-       set overridden_parent_infos = cxx.overridden_elements|type_info(attribute='parent.type', error=False)|reject('none') -%}
  {%-       set ancestors = cxx.parent.ancestors|type_info(error=False)|reject('none')|map(attribute='cxx.type_name') -%}
  {%-       for parent_info in overridden_parent_infos -%}
  {%-         if exclude_interface -%}
  {%-           if parent_info.has_api and parent_info.vars.action != 'gen_interface' and parent_info.cxx.type_name in ancestors -%}
                  {{'override '}}
  {%-             break -%}
  {%-           endif -%}
  {%-         else -%}
  {%-           if parent_info.has_api and parent_info.cxx.type_name in ancestors -%}
                  {{'override '}}
  {%-             break -%}
  {%-           endif -%}
  {%-         endif -%}
  {%-       endfor -%}
  {%-     endif -%}
  {%-   endif -%}
  {%- endmacro -%}


templates: |
  {%- macro get_template_postfix() -%}
  {%-   if cxx.is_template and template_choice -%}
  {%-     for value in template_choice.values() -%}
  {%-       if value is string -%}
              {{get_type_converter(value).custom.tname}}
  {%-       else -%}
              {{value}}
  {%-       endif -%}
  {%-     endfor -%}
  {%-   endif -%}
  {%- endmacro -%}
  {%- macro get_template_getter_name() -%}
  {%-   if cxx.is_template and template_choice -%}
  {%-     set values = template_choice.values()|list -%}
  {%-     for template_arg_name in template_args_postfixes -%}
  {%-       if template_arg_name is not none -%}
            {{template_arg_name}}
  {%-       else -%}
  {%-         if template_arg_name is string -%}
                {{get_type_converter(value).custom.tname}}
  {%-         else -%}
                {{values[loop.index]}}
  {%-         endif -%}
  {%-       endif -%}
  {%-     endfor -%}
  {%-   endif -%}
  {%- endmacro -%}
  {%- macro gen_template_args_snippets(arg_types, section_name, full_package=none) -%}
  {%-   for arg_type in arg_types -%}
  {%-     set arg_converter = get_type_converter(arg_type)|attr(section_name) -%}
  {%-     if arg_converter is defined -%}
            {{arg_converter.snippet(full_package=full_package)}}
  {%-     endif -%}
  {%-   endfor -%}
  {%- endmacro -%}
  {%- macro gen_template_instantiation(cxx, template_choice) -%}
  {%-   set comma = joiner(', ') -%}
  <
  {%-   for param in cxx.template_parameters -%}
  {{comma()}}{{template_choice.get(param)}}
  {%-   endfor -%}
  >
  {%- endmacro -%}

includes:
  cxx: |
    {%- macro gen_include(converter) -%}
    {%-   if converter and converter.cxx_include is defined -%}
            {{marker}}{{converter.cxx_include.snippet()}}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro collect_includes(converter, includes) -%}
    {%-   if converter.cxx_include is defined -%}
    {%-     do includes.append(converter.cxx_include.snippet()) -%}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro collect_desc_includes(converter, desc_includes) -%}
    {%-   if converter.type_info.has_api -%}
    {%-     set vars_descendants = converter.type_info.vars.descendants -%}
    {%-     for descendant in (vars_descendants if vars_descendants is not none else converter.type_info.descendants) -%}
    {%-       do collect_includes(get_type_converter(descendant), desc_includes) -%}
    {%-     endfor -%}
    {%-   endif -%}
    {%- endmacro -%}
  target_language: |
    {%- macro collect_import_converters(converter, import_converters, gen_for_impl=false) -%}
    {%-   set parent_converter = get_type_converter(converter.type_info.cxx.parent_type, error=False) if converter.type_info.cxx.parent_type else none -%}
    {%-   if parent_converter -%}
    {#-     in case of nested cases we don't need `gen_for_impl` anymore, so we don't pass it deeper -#}
    {%-     do collect_import_converters(parent_converter, import_converters) -%}
    {%-   else -%}
    {%-     do import_converters.append((converter, gen_for_impl)) -%}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro collect_desc_import_converters(converter, desc_import_converters) -%}
    {%-   if converter.type_info.has_api and converter.type_info.vars.descendants is defined -%}
    {%-     for descendant in (converter.type_info.vars.descendants if converter.type_info.vars.descendants is not none else converter.type_info.descendants) -%}
    {%-       do collect_import_converters(get_type_converter(descendant), desc_import_converters, gen_for_impl=true) -%}
    {%-     endfor -%}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro gen_import_by_lang(converter, language) -%}
    {%-   set lang_include = converter|attr(language + '_include') -%}
    {%-   if lang_include is defined -%}
            {{marker}}{{lang_include.snippet(full_package=vars.full_package)}}
    {%-   endif -%}
    {%- endmacro -%}

global_declarations:
  class: |
    {%- macro collect_include_converters(converter, include_converters) -%}
    {%-   if converter -%}
    {%-     if converter.type_info.has_api -%}
    {%-       do include_converters.append(converter) -%}
    {%-     endif -%}
    {%-     for arg in converter.template_args -%}
    {%-       if converter.template_args_kinds[loop.index - 1] != ElementKind.TEMPLATE_NON_TYPE_PARAMETER -%}
    {%-         do collect_include_converters(get_type_converter(arg, error=False), include_converters) -%}
    {%-       endif -%}
    {%-     endfor -%}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro collect_desc_include_converters(desc_converter, desc_include_converters) -%}
    {%-   if desc_converter -%}
    {%-     if desc_converter.type_info.has_api -%}
    {%-       set vars_descendants = desc_converter.type_info.vars.descendants -%}
    {%-       for descendant in (vars_descendants if vars_descendants is not none else desc_converter.type_info.descendants) -%}
    {%-         do collect_include_converters(get_type_converter(descendant), desc_include_converters) -%}
    {%-       endfor -%}
    {%-     endif -%}
    {%-     for arg in desc_converter.template_args -%}
    {%-       if desc_converter.template_args_kinds[loop.index - 1] != ElementKind.TEMPLATE_NON_TYPE_PARAMETER -%}
    {%-         do collect_desc_include_converters(get_type_converter(arg, error=False), desc_include_converters) -%}
    {%-       endif -%}
    {%-     endfor -%}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro gen_glob_decl() -%}
    {%-   set desc_include_converters = [] -%}
    {%-   do collect_desc_include_converters(get_type_converter(cxx.type), desc_include_converters) -%}
    {%-   for desc_converter in desc_include_converters -%}
    {%-     if desc_converter.type_info.vars.c_file_fullname != vars.c_file_fullname -%}
              {{marker}}{{'extern const char* ' + desc_converter.cxx_type_name_global.snippet() + ';'}}
    {%-     endif -%}
    {%-   endfor -%}
    {%- endmacro -%}
  method: |
    {%- macro collect_type_converters(converter, result_type_converters) -%}
    {%-   if converter and converter.type_info.has_api -%}
    {%-     do result_type_converters.append(converter) -%}
    {%-   endif -%}
    {%-   if converter -%}
    {%-     for arg in converter.template_args -%}
    {%-       if converter.template_args_kinds[loop.index - 1] != ElementKind.TEMPLATE_NON_TYPE_PARAMETER -%}
    {%-         set arg_converter = get_type_converter(arg, error=False) -%}
    {%-         if arg_converter -%}
    {%-           do collect_type_converters(arg_converter, result_type_converters) -%}
    {%-         endif -%}
    {%-       endif -%}
    {%-     endfor -%}
    {%-   endif -%}
    {%- endmacro -%}
    {%- macro _gen_glob_decl(type_converters) -%}
    {%-   for type_conv in type_converters -%}
    {#-   `cxx_type_name_global` is not defined for enum types -#}
    {%-     if type_conv.cxx_type_name_global is defined and type_conv.type_info.vars.c_file_fullname != vars.c_file_fullname -%}
              {{marker}}{{'extern const char* ' + type_conv.cxx_type_name_global.snippet() + ';'}}
    {%-     endif -%}
    {%-   endfor -%}
    {%- endmacro -%}
    {%- macro gen_glob_decl() -%}
    {#-   `result_type` is none for constructors -#}
    {%-   if cxx.result_type -%}
    {%-     set result_type_converters = [] -%}
    {%-     do collect_type_converters(get_type_converter(cxx.result_type), result_type_converters) -%}
            {{_gen_glob_decl(result_type_converters)}}
    {%-   endif -%}
    {#-   `vars.throws` is not defiend for property getters/setters -#}
    {%-   if vars.throws is defined and not 'no_throw' in vars.throws -%}
            {{_gen_glob_decl(vars.throws|type_converter)}}
    {%-   endif -%}
    {%-   if setter is defined and not 'no_throw' in setter.vars.throws -%}
            {{_gen_glob_decl(setter.vars.throws|type_converter)}}
    {%-   endif -%}
            {{_gen_glob_decl([get_type_converter('std::exception')])}}
    {%- endmacro -%}

forward_declarations:
  method: |
    {%- macro collect_fwd_decl_converters(converter, fwd_decl_converters) -%}
    {#-   Type comparison is done when the type has descendants. Forward decl is not needed when the object recover function is generated in the same file as current function/method. -#}
    {%-   if converter.type_info.has_api and converter.type_info.vars.descendants is defined and (converter.type_info.vars.descendants if converter.type_info.vars.descendants is not none else converter.type_info.descendants) and vars.c_file_fullname != converter.type_info.vars.c_file_fullname -%}
    {%-     do fwd_decl_converters.append(converter) -%}
    {%-   endif -%}
    {%-   for arg in converter.template_args -%}
    {%-     if converter.template_args_kinds[loop.index - 1] != ElementKind.TEMPLATE_NON_TYPE_PARAMETER -%}
    {%-       set arg_converter = get_type_converter(arg, error=False) -%}
    {%-       if arg_converter -%}
    {%-         do collect_fwd_decl_converters(arg_converter, fwd_decl_converters) -%}
    {%-       endif -%}
    {%-     endif -%}
    {%-   endfor -%}
    {%- endmacro -%}
    {%- macro gen_fwd_decl() -%}
    {%-   set fwd_decl_converters = [] -%}
    {%-   for arg in cxx.args -%}
    {%-     do collect_fwd_decl_converters(get_type_converter(arg.type), fwd_decl_converters) -%}
    {%-   endfor -%}
    {%-   for fwd_decl_converter in fwd_decl_converters -%}
    {%-     set converter = get_type_converter('std::shared_ptr<' + fwd_decl_converter.type_info.cxx.type_name + '>') if fwd_decl_converter.type_info.vars.shared_ref else fwd_decl_converter -%}
            {{marker}}{{converter.cxx_obj_recover_func_decl.snippet(is_fwd_decl=True)}};
    {%-   endfor -%}
    {%- endmacro -%}
  getter: |
    {%- macro collect_fwd_decl_converters(converter, fwd_decl_converters) -%}
    {#-   Type comparison is done when the type has descendants. Forward decl is not needed when the object recover function is generated in the same file as current getter/setter. -#}
    {%-   if converter.type_info.has_api and converter.type_info.vars.descendants is defined and (converter.type_info.vars.descendants if converter.type_info.vars.descendants is not none else converter.type_info.descendants) and vars.c_file_fullname != converter.type_info.vars.c_file_fullname -%}
    {%-     do fwd_decl_converters.append(converter) -%}
    {%-   endif -%}
    {%-   for arg in converter.template_args -%}
    {%-     if converter.template_args_kinds[loop.index - 1] != ElementKind.TEMPLATE_NON_TYPE_PARAMETER -%}
    {%-       set arg_converter = get_type_converter(arg, error=False) -%}
    {%-       if arg_converter -%}
    {%-         do collect_fwd_decl_converters(arg_converter, fwd_decl_converters) -%}
    {%-       endif -%}
    {%-     endif -%}
    {%-   endfor -%}
    {%- endmacro -%}
    {%- macro gen_fwd_decl() -%}
    {%-   set fwd_decl_converters = [] -%}
    {%-   if setter is defined -%}
    {%-     do collect_fwd_decl_converters(get_type_converter(cxx.result_type), fwd_decl_converters) -%}
    {%-   endif -%}
    {%-   for fwd_decl_converter in fwd_decl_converters -%}
    {%-     set converter = get_type_converter('std::shared_ptr<' + fwd_decl_converter.type_info.cxx.type_name + '>') if fwd_decl_converter.type_info.vars.shared_ref else fwd_decl_converter -%}
            {{marker}}{{converter.cxx_obj_recover_func_decl.snippet(is_fwd_decl=True)}};
    {%-   endfor -%}
    {%- endmacro -%}
