/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 05/12/2022-10:33.
 * Please do not change it manually.
 */

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>

#include "cxx/getters/person.hpp"

namespace py = pybind11;

void bindExamplesLibGettersPersonPygen(py::module& m) {
    {
        using namespace cppbind::example;
        py::class_<cppbind::example::Person, std::shared_ptr<cppbind::example::Person>> person(m, "Person");
        
        person.def(py::init<const std::string &, const std::string &, int>(), py::arg("name"), py::arg("email"), py::arg("age"));

        person.def_property("name", py::cpp_function(&cppbind::example::Person::fullName, py::return_value_policy::reference_internal), &cppbind::example::Person::setFullName);
        person.def_readonly("email", &cppbind::example::Person::_email, py::return_value_policy::reference_internal);
        person.def_readwrite("age", &cppbind::example::Person::_age, py::return_value_policy::reference_internal);
    }
} /* bindExamplesLibGettersPersonPygen */
