/*
 * This file was generated by iegen on 05/17/2021-16:00.
 * Please do not change it manually.
 */

#ifndef _C_component_WRAPPER_
#define _C_component_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_Component(void* _Nonnull cself);
    void* _Nonnull create_Component(void* _Nonnull parent, char* _Nonnull name);
#if __cplusplus
}
#endif
#endif /* ifndef _C_component_WRAPPER_ */