/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 04/25/2022-05:25.
 * Please do not change it manually.
 */

#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <cxxabi.h>
#include <memory>
#include <type_traits>
#include "swift/wrappers/templates/c_my_stack.h"
#include "cxx/templates/stack_usage.hpp"
#include "cxx/simple/project.hpp"
#include "cxx/simple/task.hpp"

extern const char* IEGEN_STD_STDEXCEPTION;

const char* IEGEN_IEGEN_EXAMPLE_MYSTACKPROJECT = "iegen::example::MyStack<iegen::example::Project>";
const char* IEGEN_IEGEN_EXAMPLE_MYSTACKTASK = "iegen::example::MyStack<iegen::example::Task>";

using namespace iegen::example;

IEGenCObject create_IegenExample_MyStackProject(IEGenCObject* _Nonnull iegen_err) {
    try {
        auto this_object = new iegen::example::MyStack<iegen::example::Project>();
        return {strdup(IEGEN_IEGEN_EXAMPLE_MYSTACKPROJECT), this_object};
    } catch (const std::exception& e) {
        iegen_err->type = strdup(IEGEN_STD_STDEXCEPTION);
        iegen_err->ptr = new std::exception(e);
    } catch (...) {
        iegen_err->type = strdup("Uncaught Exception");
    }
    IEGenCObject result {};
    return result;
}

IEGenCObject create_IegenExample_MyStackTask(IEGenCObject* _Nonnull iegen_err) {
    try {
        auto this_object = new iegen::example::MyStack<iegen::example::Task>();
        return {strdup(IEGEN_IEGEN_EXAMPLE_MYSTACKTASK), this_object};
    } catch (const std::exception& e) {
        iegen_err->type = strdup(IEGEN_STD_STDEXCEPTION);
        iegen_err->ptr = new std::exception(e);
    } catch (...) {
        iegen_err->type = strdup("Uncaught Exception");
    }
    IEGenCObject result {};
    return result;
}

