/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 05/12/2022-10:26.
 * Please do not change it manually.
 */

#ifndef _C_wrapper_WRAPPER_
#define _C_wrapper_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_CppbindExample_WrapperPairStrings(CppBindCObject cself, bool owner);

    CppBindCObject create_CppbindExample_WrapperPairStrings(CppBindCDataPair value, CppBindCObject* _Nonnull cppbind_err);
    CppBindCDataPair _prop_get_CppbindExample_WrapperPairStrings_value(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);

    void _prop_set_CppbindExample_WrapperPairStrings_value(CppBindCObject cself, CppBindCDataPair value, CppBindCObject* _Nonnull cppbind_err);

    void release_CppbindExample_WrapperPairIntInt(CppBindCObject cself, bool owner);

    CppBindCObject create_CppbindExample_WrapperPairIntInt(CppBindCDataPair value, CppBindCObject* _Nonnull cppbind_err);
    CppBindCDataPair _prop_get_CppbindExample_WrapperPairIntInt_value(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);

    void _prop_set_CppbindExample_WrapperPairIntInt_value(CppBindCObject cself, CppBindCDataPair value, CppBindCObject* _Nonnull cppbind_err);

    void release_CppbindExample_WrapperString(CppBindCObject cself, bool owner);

    CppBindCObject create_CppbindExample_WrapperString(char* _Nonnull value, CppBindCObject* _Nonnull cppbind_err);
    char* _Nonnull _prop_get_CppbindExample_WrapperString_value(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);

    void _prop_set_CppbindExample_WrapperString_value(CppBindCObject cself, char* _Nonnull value, CppBindCObject* _Nonnull cppbind_err);

#if __cplusplus
}
#endif
#endif /* ifndef _C_wrapper_WRAPPER_ */
