prefix:
  inheritable: true
  default: null
  allowed_on: [ class, class_template, struct, struct_template, enum ]

file:
  inheritable: true
  default: '{{file_name}}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

file_full_name:
  inheritable: true
  default: '{{file_full_name}}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

module:
  inheritable: false
  default: '{{module_name}}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

package:
  inheritable: true
  default: 'undefined'
  allowed_on: [ dir, class, class_template, struct, struct_template, enum, function, function_template ]

name:
  inheritable: false
  type: string
  default: '{{object_name}}'

interface_name:
  inheritable: false
  type: string
  default: 'I{{object_name}}'
  allowed_on: [ class, class_template, struct, struct_template ]

include:
  inheritable: false
  array: true
  default: [ ]
  allowed_on: [ dir, class, class_template, struct, struct_template, enum ]

code_fragment:
  inheritable: false
  array: true
  default: []
  allowed_on: [ dir ]

include_cxx:
  inheritable: false
  array: true
  default: [ ]
  allowed_on: [ class, class_template, struct, struct_template ]

shared_ref:
  inheritable: true
  default: false
  type: bool
  allowed_on: [ class, class_template, struct, struct_template ]

template:
  inheritable: true
  default: null
  type: dict
  allowed_on: [ class_template, struct_template, function_template ]

is_operator:
  inheritable: false
  default: '{{is_operator}}'
  type: bool
  allowed_on: [ cxx_method, function_template ]

is_exception:
  inheritable: false
  default: false
  type: bool
  allowed_on: [ class, class_template, struct, struct_template ]

throws:
  inheritable: false
  array: true
  allowed_on: [ function, function_template, cxx_method ]
  required_on: [ function, function_template, cxx_method ]

nullable_return:
  inheritable: false
  default: false
  type: bool
  allowed_on: [ cxx_method, function, function_template, field ]

nullable_arg:
  inheritable: false
  default: [ ]
  array: true
  allowed_on: [ cxx_method, constructor, function, function_template ]