prefix:
  inheritable: true
  default: null
  allowed_on: [ class, class_template, struct, struct_template, enum ]

file:
  inheritable: false
  default: '{file_name}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

file_full_name:
  inheritable: true
  default: '{file_full_name}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

module:
  inheritable: false
  default: '{module_name}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

package:
  inheritable: true
  default: 'undefined'
  allowed_on: [ class, class_template, struct, struct_template, enum, function_template ]

name:
  inheritable: false
  type: string
  default: '{object_name}'

include:
  inheritable: true
  array: true
  default: [ ]
  allowed_on: [ class, class_template, struct, struct_template, enum]

shared_ref:
  inheritable: true
  default: false
  type: bool
  allowed_on: [ class, class_template, struct, struct_template ]

template:
  inheritable: true
  default: null
  type: json
  allowed_on: [ class_template, struct_template, function_template ]
