cxx_include: |
  {%- macro gen_cxx_include(vars) -%}
  {%- if vars.include_cxx|default([]) -%}
  {{marker}}{{vars.include_cxx|select('match_regexp', '^<.*>$', '^".*"$')|format_list('#include {}')|join_unique}}
  {{marker}}{{vars.include_cxx|reject('match_regexp', '^<.*>$', '^".*"$')|format_list('#include "{}"')|join_unique}}
  {%- endif -%}
  {%- endmacro -%}