action:
  inheritable: false
  default: null
  allowed_on: [ cxx, file_system ]

file:
  inheritable: true
  default: '{{_file_name}}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

file_full_name:
  inheritable: true
  default: '{{_file_full_name}}'
  allowed_on: [ class, class_template, struct, struct_template, enum ]

package:
  inheritable: true
  default: 'undefined'
  allowed_on: [ dir, file, class, class_template, struct, struct_template, enum, function, function_template ]

name:
  inheritable: false
  type: string
  default: '{{_object_name}}'
  allowed_on: [ cxx, file_system ]

interface_name:
  inheritable: false
  type: string
  default: 'I{{_object_name}}'
  allowed_on: [ class, class_template, struct, struct_template ]

include:
  inheritable: false
  array: true
  default: [ ]
  allowed_on: [ dir, file, class, class_template, struct, struct_template, enum ]

code_fragment:
  inheritable: false
  array: true
  default: []
  allowed_on: [ dir, file ]

include_cxx:
  inheritable: false
  array: true
  default: [ ]
  allowed_on: [ class, class_template, struct, struct_template ]

shared_ref:
  inheritable: true
  default: false
  type: bool
  allowed_on: [ class, class_template, struct, struct_template ]

template:
  inheritable: true
  default: null
  type: dict
  allowed_on: [ class_template, struct_template, function_template ]

is_operator:
  inheritable: false
  default: '{{_is_operator}}'
  type: bool
  allowed_on: [ cxx_method, function_template ]

is_exception:
  inheritable: false
  default: false
  type: bool
  allowed_on: [ class, class_template, struct, struct_template ]

throws:
  inheritable: false
  array: true
  allowed_on: [ function, function_template, cxx_method ]
  required_on: [ function, function_template, cxx_method ]

bases_list:
  inheritable: false
  array: true
  default: [ ]
  allowed_on: [ class, class_template, struct, struct_template ]

nullable_return:
  inheritable: false
  default: false
  type: bool
  allowed_on: [ cxx_method, function, function_template, field ]

nullable_arg:
  inheritable: false
  default: [ ]
  array: true
  allowed_on: [ cxx_method, constructor, function, function_template ]

project_dir:
  inheritable: True
  default: '{{_current_working_dir}}'
  allowed_on: [ dir ]

project_link:
  inheritable: True
  default: '{{_get_git_repo_url(project_dir)}}'
  allowed_on: [ dir ]

comment_del_regex:
  inheritable: true
  array: true
  default:
    - '\s*\\internal([\s\S]*?)\\endinternal\s*'
    - '\s*\\internal[\s\S]*'
  allowed_on: [ cxx, file_system, root ]

comment:
  inheritable: false
  default:
    python: |
      {%- set regex = comment_del_regex|join('|') -%}
      {{_pure_comment|replace_regex(regex, '')}}
      {%- if _file_full_name and path.isfile(_file_full_name) and project_dir is defined %}
      Documentation generated from: `{{path.relpath(_file_full_name, project_dir)}}#L{{_line_number}}
      <{{project_link}}/{{path.relpath(_file_full_name, project_dir)}}#L{{_line_number}}>`_
      {%- endif %}
    else: |
      {%- set regex = comment_del_regex|join('|') -%}
      {{_pure_comment|replace_regex(regex, '')}}

banner_comment:
  inheritable: false
  default: |
    This file is generated by iegen on {{_output_modification_time}}.
    Please do not change it manually.
  allowed_on: [ cxx, file_system ]

out_prj_dir:
  inheritable: true
  default: wr_out
  allowed_on: [ root ]

run_dir:
  inheritable: true
  default: example_lib
  allowed_on: [ root ]

cxx_out_dir:
  inheritable: true
  default: '{{path.join(out_prj_dir, run_dir, "cxx_out")}}'
  allowed_on: [ root ]

out_dir:
  inheritable: true
  default:
    kotlin: '{{path.join(out_prj_dir, run_dir, "android", run_dir, "source/main/java")}}'
    python: '{{path.join(out_prj_dir, "python", run_dir, "src")}}'
    swift: '{{path.join(out_prj_dir, "swift")}}'
  allowed_on: [ root ]

cxx_base_out_dir:
  inheritable: true
  default: null
  allowed_on: [ root ]

package_prefix:
  inheritable: true
  default:
    kotlin: com.picsart.example_lib
    python: example_lib
    swift: com.picsart.example_lib
  allowed_on: [ root ]

helpers_package_prefix:
  inheritable: true
  default: '{{package_prefix}}'
  allowed_on: [ root ]

helpers_include_prefix:
  inheritable: true
  default: '{{helpers_package_prefix}}'
  allowed_on: [ root ]

common_helpers_dir:
  inheritable: true
  default: std_helpers
  allowed_on: [ root ]

cxx_helpers_dir:
  inheritable: true
  default:
    swift: '{{path.join(common_helpers_dir, "swift/cxx")}}'
    else: '{{path.join(common_helpers_dir, "cxx")}}'
  allowed_on: [ root ]

helpers_dir:
  inheritable: true
  default:
    kotlin: '{{path.join(common_helpers_dir, "kotlin")}}'
    python: '{{path.join(common_helpers_dir, "python")}}'
    swift: '{{path.join(common_helpers_dir, "swift")}}'
  allowed_on: [ root ]

cxx_base_dir:
  inheritable: true
  default: base
  allowed_on: [ root ]

file_postfix:
  inheritable: true
  default: _gen
  allowed_on: [ root ]

extension:
  inheritable: true
  default:
    kotlin: kt
    python: py
    swift: swift
  allowed_on: [ root ]

pybind_module:
  inheritable: true
  default:
    python: example_lib
    else: null
  allowed_on: [ root ]

c_wrapper_lib_name:
  inheritable: true
  default:
    swift: CWrapper
    kotlin: wrapper_jni
    else: null
  allowed_on: [ root, file_system ]

clang_args:
  inheritable: false
  default: []
  allowed_on: [ root ]
  array: true

src_glob:
  inheritable: false
  default:
    - ./examples/example_cxx/**/*.h*
  allowed_on: [ root ]
  array: true

src_exclude_glob:
  inheritable: false
  default: [ ]
  allowed_on: [ root ]
  array: true

include_dirs:
  inheritable: false
  default:
    - .
  allowed_on: [ root ]
  array: true
