/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 12/05/2021-09:44.
 * Please do not change it manually.
 */

#ifndef _C_host_WRAPPER_
#define _C_host_WRAPPER_

#include "c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_Host(CObject cself);

    CObject create_Host();
    char* _Nonnull _func_Host_hello(CObject cself, CObject  user, ErrorObj* _Nonnull err);
    char* _Nonnull _func_Host_welcome(CObject cself, CObject  user, ErrorObj* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_host_WRAPPER_ */