/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 03/07/2022-14:41.
 * Please do not change it manually.
 */

#ifndef _C_custom_exceptions_WRAPPER_
#define _C_custom_exceptions_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_IegenExample_SimpleBaseException(IEGenCObject cself, bool owner);

    IEGenCObject create_IegenExample_SimpleBaseException(int err_num, IEGenCObject* _Nonnull err);
    int _func_IegenExample_SimpleBaseException_errNum(IEGenCObject cself, IEGenCObject* _Nonnull err);

    IEGenCObject create_IegenExample_SimpleChildException(int err_num, IEGenCObject* _Nonnull err);
    int _func_IegenExample_SimpleChildException_errNum(IEGenCObject cself, IEGenCObject* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_custom_exceptions_WRAPPER_ */
