cc_library(
    name = "sw_examples_wrapper",
    srcs = glob(["**/*.c*"]),
    hdrs = glob(["**/*.h*"]),
    tags = ["swift_module=CWrapper"],
    visibility = ["//visibility:public"],
    deps = [
        "//cxx:cc_examples_library",
    ],
)
