void:
  types:
    kotlin: Unit
    jni: void
    jdk: Unit
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

bool:
  custom:
    pname: Boolean
  types:
    kotlin: Boolean
    jni: jboolean
    jdk: Boolean
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

int:
  custom:
    pname: Int
  types:
    kotlin: Int
    jni: jint
    jdk: Int
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

unsigned int:
  custom:
    pname: Long
  types:
    kotlin: Long
    jni: jlong
    jdk: Long
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

short:
  custom:
    pname: Short
  types:
    kotlin: Short
    jni: jshort
    jdk: Short
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

long:
  custom:
    pname: Long
  types:
    kotlin: Long
    jni: jlong
    jdk: Long
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

long long:
  long

unsigned long:
  long

float:
  custom:
    pname: Float
  types:
    kotlin: Float
    jni: jfloat
    jdk: Float
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

double:
  custom:
    pname: Double
  types:
    kotlin: Double
    jni: jdouble
    jdk: Double
  converters:
    jni_to_cxx:
    cxx_to_jni:
    kotlin_to_jdk:
    jdk_to_kotlin:

char:
  custom:
    pname: Char
  types:
    kotlin: Char
    jni: jbyte
    jdk: Char
  converters:
    jni_to_cxx: |
      char {{target_name}} = static_cast<char>({{name}});
    cxx_to_jni: |
      {{target_type_name}} {{target_name}} = static_cast<jbyte>({{name}});
    kotlin_to_jdk:
    jdk_to_kotlin:
