my_types: &my_types
    std::mapdd:
      custom:
        pname: Intd
      kotlin:
        type_info: Intd
      jni:
        type_info: jintd
      jdk:
        type_info: Intd
      jni_to_cxx: 
      cxx_to_jni: 
      kotlin_to_jdk:
      jdk_to_kotlin:


init:
  actions: !include actions.yaml

codes: !include code_snippets.yaml

types:
  !join
    - !include "*_types.yaml"
    - *my_types
    - std::mapd:
        custom:
          pname: Intd
        kotlin:
          type_info: Intd
        jni:
          type_info: jintd
        jdk:
          type_info: Intd
        jni_to_cxx: 
        cxx_to_jni: 
        kotlin_to_jdk:
        jdk_to_kotlin:
