nlohmann::json:
  custom:
    pname: json
  kotlin:
    type_info: String
  jni:
    type_info: jstring
  jdk:
    type_info: String
  jni_to_cxx: |
    auto {{target_name}} = nlohmann::json::parse(iegen::jni_to_string(env, {{name}}))
  cxx_to_jni: |
    {{target_type_name}} {{target_name}} = iegen::string_to_jni(env, {{name}}.dump(4));
  kotlin_to_jdk:
  jdk_to_kotlin:

json:
  nlohmann::json
