"""
,--.,------. ,----.   ,------.,--.  ,--. 
|  ||  .---''  .-.|   |  .---'|  ,'.|  | 
|  ||  `--, |  | .---.|  `--, |  |' '  | 
|  ||  `---.'  '--'  ||  `---.|  | `   | 
`--'`------' `------' `------'`--'  `--' 

This file is generated by iegen on 08/05/2021-12:29.
Please do not change it manually.
"""
from .vehicle_pygen import Vehicle
from .bicycle_pygen import Bicycle
from .parallelogram_pygen import Parallelogram
from .rectangle_pygen import Rectangle
from .rhombus_pygen import RhombusFigure
from .square_pygen import Square
from .usage_pygen import GeometricFigure
from .usage_pygen import MyVehicle
