"""
,--.,------. ,----.   ,------.,--.  ,--. 
|  ||  .---''  .-.|   |  .---'|  ,'.|  | 
|  ||  `--, |  | .---.|  `--, |  |' '  | 
|  ||  `---.'  '--'  ||  `---.|  | `   | 
`--'`------' `------' `------'`--'  `--' 

This file is generated by iegen on 07/28/2021-18:55.
Please do not change it manually.
"""

from __future__ import annotations

from typing import *

import examples.inheritance.parallelogram as pybind_parallelogram_pygen
from examples_lib.bind_utils import *
from examples_lib.metaclass import *
from abc import abstractmethod


class Parallelogram(metaclass=OriginalMethodsMetaclass):
    """
    Documentation generated from: `cxx/inheritance/parallelogram.hpp#L12
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/parallelogram.hpp#L12>`_
    """
    @abstractmethod
    def __init__(self, *args, **kwargs):
        pass
    
    @property
    @bind
    def area(self) -> float:
        """
        Documentation generated from: `cxx/inheritance/parallelogram.hpp#L22
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/parallelogram.hpp#L22>`_
        """
        pass
    
    @bind
    def perimeter(self) -> float:
        """
        Documentation generated from: `cxx/inheritance/parallelogram.hpp#L29
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/parallelogram.hpp#L29>`_
        """
        pass
