"""
,--.,------. ,----.   ,------.,--.  ,--.
|  ||  .---''  .-.|   |  .---'|  ,'.|  |
|  ||  `--, |  | .---.|  `--, |  |' '  |
|  ||  `---.'  '--'  ||  `---.|  | `   |
`--'`------' `------' `------'`--'  `--'

This file is generated by iegen on 12/04/2021-12:25.
Please do not change it manually.
"""
from __future__ import annotations

from typing import *

import examples.inheritance.rectangle as pybind_rectangle_pygen
import examples_lib.inheritance.parallelogram_pygen as parallelogram
from examples_lib.iegen.bind_utils import *
from examples_lib.iegen.metaclass import *


class Rectangle(parallelogram.Parallelogram, metaclass=OriginalMethodsMetaclass):
    """
    Documentation generated from: `cxx/inheritance/rectangle.hpp#L13
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/rectangle.hpp#L13>`_
    """
    
    @bind
    def __init__(self, length: float, width: float):
        """
        Documentation generated from: `cxx/inheritance/rectangle.hpp#L19
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/rectangle.hpp#L19>`_
        """
        pass
    
    @property
    @bind
    def area(self) -> float:
        """
        Documentation generated from: `cxx/inheritance/rectangle.hpp#L29
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/rectangle.hpp#L29>`_
        """
        pass

    @property
    @bind
    def length(self) -> float:
        """
        Documentation generated from: `cxx/inheritance/rectangle.hpp#L42
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/rectangle.hpp#L42>`_
        """
        pass

    @property
    @bind
    def width(self) -> float:
        """
        Documentation generated from: `cxx/inheritance/rectangle.hpp#L51
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/inheritance/rectangle.hpp#L51>`_
        """
        pass
