site_name: CppBind
site_url: https://cppbind.io/
use_directory_urls: false
nav:
  - Introduction: index.md
  - First Steps:
    - Supported languages: first_steps/supported_languages.md
    - Installation: first_steps/installation.md
    - “Hello user” tutorial: first_steps/hello_user.md
    - “Array” tutorial: first_steps/array_tutorial.md
  - Main Features:
    - Functions: main_features/functions.md
    - Classes/Structs: main_features/classes.md
    - Enums: main_features/enums.md
    - Inheritance: main_features/inheritance.md
    - Object type preservation: main_features/object_type_preservation.md
    - Exception handling: main_features/exception_handling.md
    - Templates: main_features/templates.md
    - Operator Overloading: main_features/operators.md
    - Memory management: main_features/memory_management.md
    - Standard library types: main_features/standard_library_types.md
    - Generation instructions: main_features/gen_actions.md
    - Variable definitions: main_features/var_def.md
    - Command line interface: main_features/command_line_interface.md
    - Extra files generation:
      - Building Swift bindings with Xcode: main_features/extra_files_generation/swift_example_with_modulemap.md
  - Advanced Topics:
    - CppBind snippets:
      - Code snippets: advanced_topics/cppbind_snippets/code_snippets.md
      - Type converter snippets: advanced_topics/cppbind_snippets/type_converter_snippets.md
      - Writing custom type converter: advanced_topics/cppbind_snippets/custom_types.md
      - Action snippets: advanced_topics/cppbind_snippets/action_snippets.md
      - Yaml configuration file management: advanced_topics/cppbind_snippets/yaml_management.md
      - CppBind jinja helpers: advanced_topics/cppbind_snippets/cppbind_jinja_helpers.md
    - Helper Python modules: advanced_topics/helper_python_modules.md
    - New language bindings generation: advanced_topics/adding_language.md
  - Configuration:
    - Application configuration: configuration/app_config.md
    - Project configuration: configuration/proj_config.md
  - Other:
    - Frequently asked questions: faqs/faq.md

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  features:
    # - navigation.sections
    - navigation.expand
  logo: _static/img/cppbind-icon.svg  
  favicon: _static/img/cppbind-icon.svg

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - attr_list
  - md_in_html
  
  - def_list
  - codehilite:
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true 

repo_url: https://github.com/PicsArt/cppbind
edit_uri: ""

copyright: Copyright &copy; <script>document.write( new Date().getFullYear() );</script> .

plugins:
  - git-revision-date-localized
  - search
  - include-markdown
