/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 09/24/2021-06:44.
 * Please do not change it manually.
 */

#include "jni.h"
#include <iostream>
#include "kotlin/wrappers/iegen_wrapper_helper.hpp"
#include "cxx/forward_decl/student.hpp"
#include "cxx/forward_decl/teacher.hpp"

using namespace iegen::example;


extern "C" JNIEXPORT void Java_com_examples_forward_1decl_student_Student_jFinalize(JNIEnv* env, jobject obj, jobjectid id){
    
    std::shared_ptr<iegen::example::Student>& jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<iegen::example::Student>*>(id);
    delete &jni_to_cxx_id;
}
extern "C" JNIEXPORT jobjectid Java_com_examples_forward_1decl_student_Student_jConstructor(JNIEnv* env, jobject obj, jstring st_name){
    jstring jjni_to_cxx_st_nameStr = (jstring)st_name;
    auto jni_to_cxx_st_name_cstr = env->GetStringUTFChars(jjni_to_cxx_st_nameStr, 0);
    const std::string & jni_to_cxx_st_name = jni_to_cxx_st_name_cstr;
    env->ReleaseStringUTFChars(jjni_to_cxx_st_nameStr, jni_to_cxx_st_name_cstr);
    iegen::example::Student* obj_ptr = new iegen::example::Student(jni_to_cxx_st_name);
    auto this_object = std::shared_ptr<iegen::example::Student>(obj_ptr);
    return reinterpret_cast<jlong>(new std::shared_ptr<iegen::example::Student>(this_object));
}
extern "C" JNIEXPORT jobjectid Java_com_examples_forward_1decl_student_Student_jConstructor_11(JNIEnv* env, jobject obj, jobjectidArray teachers){
    
    std::vector<Teacher *> jni_to_cxx_teachers;
    auto _jni_to_cxx_teachers = iegen::getLongArray(env, teachers);
    for (auto& value__jni_to_cxx_teachers : _jni_to_cxx_teachers) {
        
        auto jni_to_cxx_value__jni_to_cxx_teachers = reinterpret_cast<iegen::example::Teacher*>(value__jni_to_cxx_teachers);
        jni_to_cxx_teachers.emplace_back(jni_to_cxx_value__jni_to_cxx_teachers);
    }
    iegen::example::Student* obj_ptr = new iegen::example::Student(jni_to_cxx_teachers);
    auto this_object = std::shared_ptr<iegen::example::Student>(obj_ptr);
    return reinterpret_cast<jlong>(new std::shared_ptr<iegen::example::Student>(this_object));
}


extern "C" JNIEXPORT void Java_com_examples_forward_1decl_student_Student_jAddteacher(JNIEnv* env, jobject obj, jobjectid id, jobjectid t){
    

    auto jni_to_cxx_t = reinterpret_cast<iegen::example::Teacher*>(t);

    validateID(id);
    std::shared_ptr<iegen::example::Student>& jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<iegen::example::Student>*>(id);
    
    try {
        jni_to_cxx_id->addTeacher(jni_to_cxx_t);
        return;
    }
    catch (const std::exception& e) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF(e.what()));
    }
    catch (...) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF("Uncaught Exception"));
    }


}


extern "C" JNIEXPORT jobjectidArray Java_com_examples_forward_1decl_student_Student_jTeachers(JNIEnv* env, jobject obj, jobjectid id){
    
    validateID(id);
    std::shared_ptr<iegen::example::Student>& jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<iegen::example::Student>*>(id);
    
    try {
        auto result = jni_to_cxx_id->teachers();
        
        jobjectidArray cxx_to_jni_result = env->NewLongArray(result.size());
        size_t index_result = 0;
        for (auto& value_result : result) {
            
            iegen::example::Teacher* cxx_to_jni_value_result_baseptr = value_result;
            jobjectid cxx_to_jni_value_result = reinterpret_cast<jlong>(cxx_to_jni_value_result_baseptr);
            env->SetLongArrayRegion(cxx_to_jni_result, index_result, 1, &cxx_to_jni_value_result);
            ++index_result ;
        }
        return cxx_to_jni_result;
    }
    catch (const std::exception& e) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF(e.what()));
    }
    catch (...) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF("Uncaught Exception"));
    }

    jobjectidArray result;
    return result;
}
extern "C" JNIEXPORT jstring Java_com_examples_forward_1decl_student_Student_jName(JNIEnv* env, jobject obj, jobjectid id){
    validateID(id);
    
    std::shared_ptr<iegen::example::Student>& jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<iegen::example::Student>*>(id);
    auto result = jni_to_cxx_id->name;
    jstring cxx_to_jni_result = env->NewStringUTF(result.c_str());
    return cxx_to_jni_result;
}

extern "C" JNIEXPORT void Java_com_examples_forward_1decl_student_Student_jSetname(JNIEnv* env, jobject obj, jobjectid id, jstring value){
    validateID(id);
    
    std::shared_ptr<iegen::example::Student>& jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<iegen::example::Student>*>(id);
    
    jstring jjni_to_cxx_valueStr = (jstring)value;
    auto jni_to_cxx_value_cstr = env->GetStringUTFChars(jjni_to_cxx_valueStr, 0);
    std::string jni_to_cxx_value = jni_to_cxx_value_cstr;
    env->ReleaseStringUTFChars(jjni_to_cxx_valueStr, jni_to_cxx_value_cstr);
    jni_to_cxx_id->name = jni_to_cxx_value;
}
