

/**
 * An example class comment.
 * __API__
 * action: gen_class
 * comment: "{{_pure_comment}}\n Binding generated by iegen."
 */
class ExampleClass {
    public:
    /**
    * __API__
    * action: gen_constructor
    * throws: no_throw
    */
    ExampleClass() {}


};

