/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 11/01/2021-14:54.
 * Please do not change it manually.
 */

#include <string.h>
#include <memory>
#include "swift/wrappers/simple/c_task.h"
#include "cxx/simple/task.hpp"

using namespace iegen::example;

void release_Task(void* _Nonnull cself) {
    delete static_cast<iegen::example::Task*>(cself);
}

void* _Nonnull create_Task(char* _Nonnull title){
    auto c_to_cxx_title = std::string(title);
    free(title);
    auto this_object = new iegen::example::Task(c_to_cxx_title);
    return this_object;
}

char* _Nonnull _prop_get_Task_title(void* _Nonnull cself){
    auto c_to_cxx_cself = static_cast<iegen::example::Task*>(cself);
    const auto& result = c_to_cxx_cself->title();
    auto cxx_to_c_result = strdup(result.data());
    return cxx_to_c_result;
}

void _func_Task_setTitle(void* _Nonnull cself, char* _Nonnull title, ErrorObj* _Nonnull err){
    auto c_to_cxx_title = std::string(title);
    free(title);
  
    
    auto c_to_cxx_cself = static_cast<iegen::example::Task*>(cself);
    try {
        c_to_cxx_cself->setTitle(c_to_cxx_title);
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
}