/*
 * This file was generated by iegen on 06/09/2021-11:41.
 * Please do not change it manually.
 */

#ifndef getters_number_hpp
#define getters_number_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindNumberint(py::module& m);
void bindNumberfloat(py::module& m);

#endif