/*
 * This file was generated by iegen on 06/09/2021-11:41.
 * Please do not change it manually.
 */

#ifndef getters_one_type_template_getter_hpp
#define getters_one_type_template_getter_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindSimpleItem(py::module& m);
void bindOneTypeTemplateGetter(py::module& m);

#endif