/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 07/02/2021-09:03.
 * Please do not change it manually.
 */

#ifndef getters_one_type_template_getter_hpp
#define getters_one_type_template_getter_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindIegenExampleSimpleItem(py::module& m);
void bindIegenExampleOneTypeTemplateGetter(py::module& m);

#endif