load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "examples_usage_library",
    srcs = glob(["src/**/*.kt"]),
    visibility = ["//visibility:public"],
)
