vars:
  out_prj_dir: "."
  src_glob:
    - ./**/*.h*
  extra_headers:
    - stdexcept
    - new
    - typeinfo
  include_dirs:
    - .
  kotlin.clang_args:
    - -D__ANDROID__
  mac.kotlin.target_arch: x86_64
  mac.kotlin.clang_args:
    - -D__ANDROID__
    - --target={{target_arch}}-none-linux-android
    - --sysroot={{get_android_ndk_sysroot(getenv('ANDROID_NDK'))}}
  mac.python.clang_args:
    - --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
  mac.swift.clang_args:
    - --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
  kotlin.cxx_out_dir: "{{path.join(out_prj_dir, 'kotlin/wrappers')}}"
  kotlin.out_dir: "{{path.join(out_prj_dir, 'kotlin/src/main/java')}}"
  python.cxx_out_dir: "{{path.join(out_prj_dir, 'python/wrappers')}}"
  python.out_dir: "{{path.join(out_prj_dir, 'python/src')}}"
  swift.cxx_out_dir: "{{path.join(out_prj_dir, 'swift/wrappers')}}"
  swift.out_dir: "{{path.join(out_prj_dir, 'swift/src')}}"

type_vars:
  !join
  - !include std_exc_api.yaml

var_def:
  !join
  - !include variable_definitions.yaml

rules:
  kotlin.code_snippets:
    !join
    - !include kotlin/code_snippets.yaml
  python.code_snippets:
    !join
    - !include python/code_snippets.yaml
  swift.code_snippets:
    !join
    - !include swift/code_snippets.yaml

  kotlin.type_converters:
    !join
    - !include "kotlin/*_types.yaml"
  python.type_converters:
    !join
    - !include "python/*_types.yaml"
  swift.type_converters:
    !join
    - !include "swift/*_types.yaml"

  kotlin.actions:
    !join
    - !include kotlin/actions.yaml
  python.actions:
    !join
    - !include python/actions.yaml
  swift.actions:
    !join
    - !include swift/actions.yaml
