# Copyright (c) 2022 PicsArt, Inc.
# All rights reserved. Use of this source code is governed by a
# MIT-style license that can be found in the LICENSE file.

includes: |
  {%- macro gen_user_defined_cxx_includes(vars) -%}
  {%- if vars.include_cxx|default([]) -%}
  {{marker}}{{vars.include_cxx|select('match_regex', '^<.*>$', '^".*"$')|format_list('#include {}')|join_unique}}
  {{marker}}{{vars.include_cxx|reject('match_regex', '^<.*>$', '^".*"$')|format_list('#include "{}"')|join_unique}}
  {%- endif -%}
  {%- endmacro -%}

