/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 12/07/2021-12:30.
 * Please do not change it manually.
 */

#ifndef templates_addressable_hpp
#define templates_addressable_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindIegenExampleAddressableRoot(py::module& m);

#endif
