/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 05/12/2022-10:29.
 * Please do not change it manually.
 */

package com.examples.inheritance

import com.examples.cppbind.alias.*
import com.examples.cppbind.exceptionUtils.*
import com.examples.cppbind.exception_helpers.*


interface IBase : AutoCloseable {
    val id: Long
    fun keepCppBindReference(ref: Any)
    
    
    open fun value(): String {
        val result = IBaseHelper.jValue(id)
        
        return result
    }

    companion object {
        public fun cppbindConstructObject(id: Long, owner: Boolean = false): IBase {
            val idType = jGettypebyid(id)
            when (idType) {
                DateTime.cppbindCxxTypeName -> return DateTime(CppBindObject(id, owner))
                Date.cppbindCxxTypeName -> return Date(CppBindObject(id, owner))
                TimeImpl.cppbindCxxTypeName -> return TimeImpl(CppBindObject(id, owner))
                else -> return BaseImpl(CppBindObject(id, owner))
            }
        }
    }
}


class IBaseHelper {
    companion object {
        @JvmStatic
        external fun jValue(id: Long): String
    }
}


open class BaseImpl
internal constructor(obj : CppBindObject) : IBase {
    companion object {
        init {
            System.loadLibrary("wrapper_jni")
        }
        
        const val cppbindCxxTypeName: String = "cppbind::example::Base"
    }

    protected var cppbindObj = obj
    private var refs: MutableList<Any> = mutableListOf()

    override fun keepCppBindReference(ref: Any) {
        refs.add(ref)
    }

    override val id: Long
        get() {
            if (cppbindObj.id == 0L) {
                throw RuntimeException("Object is not allocated")
            }
            return cppbindObj.id
        }

    override fun close() {
        if (cppbindObj.owner && cppbindObj.id != 0L) {
            jFinalize(cppbindObj.id)
            cppbindObj.id = 0L
        }
    }

    /**
    * Finalize and deletes the object
    */
    protected fun finalize() {
        close()
    }
    
    ///// External wrapper functions ////////////
    private external fun jFinalize(id: Long): Unit
}

private external fun jGettypebyid(id: Long): String
