/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 10/15/2021-18:18.
 * Please do not change it manually.
 */

package com.examples.inheritance

import alias.*
import com.examples.exception_helpers.*
import exceptionUtils.*


interface IBase : AutoCloseable {
    fun getObjId(): Long
    
    
}



open class BaseImpl
internal constructor(_id: Long) : IBase {
    companion object {
        init {
            System.loadLibrary("wrapper_jni");
        }
        
    }

    protected var id = _id
    override fun getObjId(): Long {
        if (id == 0L) {
            throw RuntimeException("Object is not allocated")
        }
        return id;
    }

    override fun close() {
        if (id != 0L) {
            jFinalize(id)
            id = 0L
        }
    }

    /**
    * Finalize and deletes the object
    */
    protected fun finalize() {
        close()
    }
    
    ///// External wrapper functions ////////////
    private external fun jFinalize(id: Long): Unit
}