/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 11/30/2021-09:10.
 * Please do not change it manually.
 */

#include <string.h>
#include <cxxabi.h>
#include <memory>
#include "swift/wrappers/extra/c_object.h"
#include "cxx/extra/object.hpp"

using namespace iegen;

void release_Object(CDataObj cself) {
    delete static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
}

char* _Nonnull _func_Object_toString(CDataObj cself, ErrorObj* _Nonnull err){
    
    std::shared_ptr<iegen::Object> c_to_cxx_cself;
    c_to_cxx_cself = *static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
    try {
        const auto& result = c_to_cxx_cself->toString();
        auto cxx_to_c_result = strdup(result.data());
        return cxx_to_c_result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    char* result = nullptr;
    return result;
}

char* _Nonnull _func_Object_className(CDataObj cself, ErrorObj* _Nonnull err){
    
    std::shared_ptr<iegen::Object> c_to_cxx_cself;
    c_to_cxx_cself = *static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
    try {
        const auto& result = c_to_cxx_cself->className();
        auto cxx_to_c_result = strdup(result.data());
        return cxx_to_c_result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    char* result = nullptr;
    return result;
}

bool _func_Object_equals(CDataObj cself, CDataObj other, ErrorObj* _Nonnull err){
    
    std::shared_ptr<iegen::Object> c_to_cxx_other;
    c_to_cxx_other = *static_cast<std::shared_ptr<iegen::Object>*>(other.ptr);
  
    
    std::shared_ptr<iegen::Object> c_to_cxx_cself;
    c_to_cxx_cself = *static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
    try {
        const auto& result = c_to_cxx_cself->equals(c_to_cxx_other);
        
        return result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    bool result;
    return result;
}

unsigned long _func_Object_hash(CDataObj cself, ErrorObj* _Nonnull err){
    
    std::shared_ptr<iegen::Object> c_to_cxx_cself;
    c_to_cxx_cself = *static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
    try {
        const auto& result = c_to_cxx_cself->hash();
        
        return result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    unsigned long result;
    return result;
}

char* _Nonnull _func_Object_debugInfo(CDataObj cself, ErrorObj* _Nonnull err){
    
    std::shared_ptr<iegen::Object> c_to_cxx_cself;
    c_to_cxx_cself = *static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
    try {
        const auto& result = c_to_cxx_cself->debugInfo();
        auto cxx_to_c_result = strdup(result.data());
        return cxx_to_c_result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    char* result = nullptr;
    return result;
}

unsigned long _func_Object_bytesCount(CDataObj cself, ErrorObj* _Nonnull err){
    
    std::shared_ptr<iegen::Object> c_to_cxx_cself;
    c_to_cxx_cself = *static_cast<std::shared_ptr<iegen::Object>*>(cself.ptr);
    try {
        const auto& result = c_to_cxx_cself->bytesCount();
        
        return result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    unsigned long result;
    return result;
}