/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 12/07/2021-16:20.
 * Please do not change it manually.
 */

#include <string.h>
#include <memory>
#include "swift/wrappers/globs/c_GlobUtils.h"
#include "cxx/globs/utils.hpp"
#include "cxx/simple/project.hpp"
#include "cxx/simple/root.hpp"



char* _Nonnull _func__concat(char* _Nonnull str1, char* _Nonnull str2, ErrorObj* _Nonnull err) {
    auto ctocxxstr1 = std::string(str1);
    free(str1);
    auto ctocxxstr2 = std::string(str2);
    free(str2);
    try {
        const auto& result = ::concat(ctocxxstr1, ctocxxstr2);
        auto cxxtocresult = strdup(result.data());
        return cxxtocresult;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    char* result;
    return result;
}

int _func__maxInt(int arg0, int arg1, ErrorObj* _Nonnull err) {
    
    
    try {
        const auto& result = ::max<int>(arg0, arg1);
        
        return result;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    int result;
    return result;
}

char* _Nonnull _func__maxString(char* _Nonnull arg0, char* _Nonnull arg1, ErrorObj* _Nonnull err) {
    auto ctocxxarg0 = std::string(arg0);
    free(arg0);
    auto ctocxxarg1 = std::string(arg1);
    free(arg1);
    try {
        const auto& result = ::max<std::string>(ctocxxarg0, ctocxxarg1);
        auto cxxtocresult = strdup(result.data());
        return cxxtocresult;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    char* result;
    return result;
}

CDataPair _func_IegenExample_makePairProjectProject(void* _Nonnull arg0, void* _Nonnull arg1, ErrorObj* _Nonnull err) {
    
    auto ctocxxarg0 = static_cast<iegen::example::Project*>(arg0);
    
    auto ctocxxarg1 = static_cast<iegen::example::Project*>(arg1);
    try {
        const auto& result = iegen::example::makePair<iegen::example::Project, iegen::example::Project>(ctocxxarg0, ctocxxarg1);
        auto _first_data_cxxtocresult = new void*;
        auto _second_data_cxxtocresult = new void*;
        const auto& first_result = result.first;
        const auto& second_result = result.second;

        auto cxxtocfirst_result = const_cast<iegen::example::Project*>(first_result);

        auto cxxtocsecond_result = const_cast<iegen::example::Project*>(second_result);
        *_first_data_cxxtocresult = cxxtocfirst_result;
        *_second_data_cxxtocresult = cxxtocsecond_result;
        CDataPair cxxtocresult = { _first_data_cxxtocresult, _second_data_cxxtocresult };
        return cxxtocresult;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    CDataPair result;
    return result;
}

CDataPair _func_IegenExample_makePairRootProject(void* _Nonnull arg0, void* _Nonnull arg1, ErrorObj* _Nonnull err) {
    
    auto ctocxxarg0 = static_cast<iegen::example::Root*>(arg0);
    
    auto ctocxxarg1 = static_cast<iegen::example::Project*>(arg1);
    try {
        const auto& result = iegen::example::makePair<iegen::example::Root, iegen::example::Project>(ctocxxarg0, ctocxxarg1);
        auto _first_data_cxxtocresult = new void*;
        auto _second_data_cxxtocresult = new void*;
        const auto& first_result = result.first;
        const auto& second_result = result.second;

        auto cxxtocfirst_result = const_cast<iegen::example::Root*>(first_result);

        auto cxxtocsecond_result = const_cast<iegen::example::Project*>(second_result);
        *_first_data_cxxtocresult = cxxtocfirst_result;
        *_second_data_cxxtocresult = cxxtocsecond_result;
        CDataPair cxxtocresult = { _first_data_cxxtocresult, _second_data_cxxtocresult };
        return cxxtocresult;
    }
    catch (const std::exception& e) {
        err->err_type = 1;
        err->err_ptr = new std::exception(e);
    }
    catch (...) {
        err->err_type = -1;
    }
    CDataPair result;
    return result;
}