"""
,--.,------. ,----.   ,------.,--.  ,--.
|  ||  .---''  .-.|   |  .---'|  ,'.|  |
|  ||  `--, |  | .---.|  `--, |  |' '  |
|  ||  `---.'  '--'  ||  `---.|  | `   |
`--'`------' `------' `------'`--'  `--'

This file is generated by iegen on 12/04/2021-12:25.
Please do not change it manually.
"""
from __future__ import annotations

from typing import *

import examples.getters.person as pybind_person_pygen
from examples_lib.iegen.bind_utils import *
from examples_lib.iegen.metaclass import *


class Person(metaclass=OriginalMethodsMetaclass):
    """
    This class contains a private string field and getter/setter methods for it.
    Documentation generated from: `cxx/getters/person.hpp#L19
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L19>`_
    """
    
    @bind
    def __init__(self, name: str, email: str, age: int):
        """
        Documentation generated from: `cxx/getters/person.hpp#L25
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L25>`_
        """
        pass
    
    @property
    @bind
    def name(self) -> str:
        """
        Documentation generated from: `cxx/getters/person.hpp#L42
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L42>`_
        """
        pass

    @name.setter
    @bind
    def name(self, value: str):
        """
        Documentation generated from: `cxx/getters/person.hpp#L42
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L42>`_
        """
        pass

    @property
    @bind
    def email(self) -> str:
        """
        Documentation generated from: `cxx/getters/person.hpp#L51
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L51>`_
        """
        pass


    @property
    @bind
    def age(self) -> int:
        """
        Documentation generated from: `cxx/getters/person.hpp#L58
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L58>`_
        """
        pass

    @age.setter
    @bind
    def age(self, value: int):
        """
        Documentation generated from: `cxx/getters/person.hpp#L58
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/getters/person.hpp#L58>`_
        """
        pass
