/**
 * ,--.,------. ,----.   ,------.,--.  ,--.
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  |
 * |  ||  `--, |  | .---.|  `--, |  |' '  |
 * |  ||  `---.'  '--'  ||  `---.|  | `   |
 * `--'`------' `------' `------'`--'  `--'
 * 
 * This file is generated by iegen on 12/04/2021-12:25.
 * Please do not change it manually.
 */

#ifndef functionals_functional_example_hpp
#define functionals_functional_example_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindIegenExampleFunctionalExamples(py::module& m);

#endif