/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 05/12/2022-10:33.
 * Please do not change it manually.
 */

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>

#include "cxx/operators/counter.hpp"

namespace py = pybind11;

void bindExamplesLibOperatorsCounterPygen(py::module& m) {
    {
        using namespace cppbind::example;
        py::class_<cppbind::example::Counter> counter(m, "Counter");
        
        counter.def(py::init<int>(), py::arg("count"));

        counter.def_property_readonly("count", &cppbind::example::Counter::count, py::return_value_policy::reference_internal);
        counter.def("__add__", &cppbind::example::Counter::operator+, py::arg("counter"), py::return_value_policy::automatic);
        counter.def("__gt__", &cppbind::example::Counter::operator>, py::arg("counter"), py::return_value_policy::automatic);
        counter.def("__iadd__", &cppbind::example::Counter::operator+=, py::arg("counter"), py::return_value_policy::reference);
    }
} /* bindExamplesLibOperatorsCounterPygen */
