- type: "std::exception"
  vars: |
    action: gen_class
    python.action:
    name: StdException
    package: exception_helpers
    file: std_exc_classes
    swift.bases_list:
      - Error
    kotlin.bases_list:
      - Exception()
    {% if c_wrapper_build_name is defined -%}
    swift.include: "{{c_wrapper_build_name}}"
    {%- endif -%}
    include_cxx:
      - <stdexcept>
      - <new>
      - <typeinfo>

- type: "std::exception::what()"
  vars:
    action: gen_method
    python.action:
    throws: no_throw

- type: "std::runtime_error"
  vars:
    action: gen_class
    python.action:
    name: StdRuntimeError
    package: exception_helpers
    file: std_exc_classes

- type: "std::logic_error"
  vars:
    action: gen_class
    python.action:
    name: StdLogicError
    package: exception_helpers
    file: std_exc_classes

- type: "std::bad_alloc"
  vars:
    action: gen_class
    python.action:
    name: StdBadAlloc
    package: exception_helpers
    file: std_exc_classes

- type: "std::bad_cast"
  vars:
    action: gen_class
    python.action:
    name: StdBadCast
    package: exception_helpers
    file: std_exc_classes

- type: "std::bad_typeid"
  vars:
    action: gen_class
    python.action:
    name: StdBadTypeId
    package: exception_helpers
    file: std_exc_classes

- type: "std::overflow_error"
  vars:
    action: gen_class
    python.action:
    name: StdOverflowError
    package: exception_helpers
    file: std_exc_classes

- type: "std::range_error"
  vars:
    action: gen_class
    python.action:
    name: StdRangeError
    package: exception_helpers
    file: std_exc_classes

- type: "std::underflow_error"
  vars:
    action: gen_class
    python.action:
    name: StdUnderflowError
    package: exception_helpers
    file: std_exc_classes

- type: "std::invalid_argument"
  vars:
    action: gen_class
    python.action:
    name: StdInvalidArgument
    package: exception_helpers
    file: std_exc_classes

- type: "std::length_error"
  vars:
    action: gen_class
    python.action:
    name: StdLengthError
    package: exception_helpers
    file: std_exc_classes

- type: "std::out_of_range"
  vars:
    action: gen_class
    python.action:
    name: StdOutOfRange
    package: exception_helpers
    file: std_exc_classes

- type: "std::domain_error"
  vars:
    action: gen_class
    python.action:
    name: StdDomainError
    package: exception_helpers
    file: std_exc_classes
