/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 11/22/2022-11:22.
 * Please do not change it manually.
 */

#include <pybind11/pybind11.h>
#include "python/wrappers/example_lib/pybind_example_lib.h"

namespace py = pybind11;

void bindPybindExampleLib(py::module& m) {
    py::module_ example_lib_array_array = m.def_submodule("array", "array");

    py::module_ example_lib_array_array_array = example_lib_array_array.def_submodule("array", "array");

    bindExampleLibArrayArray(example_lib_array_array_array);
}
