cc_library(
    name = "cc_examples_library",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob([
        "**/*.hpp",
        "**/*.h",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "@nlohmann_json//:json"
    ],
)
