cc_library(
    name = "cc_examples_library",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob([
        "**/*.hpp",
        "**/*.h",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cc_examples_files",
    srcs = glob([
        "**/*.cpp",
        "**/*.h*",
    ]),
    visibility = ["//visibility:public"],
)
