/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 09/01/2021-15:29.
 * Please do not change it manually.
 */

import CWrapper
import Foundation

public protocol RhombusFigure : Parallelogram {

    
    
    
    
}
extension RhombusFigure {
    
    
}
public class RhombusFigureImpl : RhombusFigure {
    public let cself : UnsafeMutableRawPointer
    public let owner : Bool

    // internal main initializer
    internal required init(_ _cself: UnsafeMutableRawPointer, _ _owner: Bool = false) {
      self.cself = _cself
      self.owner = _owner
    }
    deinit {
      if owner {
        release_RhombusFigureImpl(cself)
      }
    }

    
    public convenience init(diagonal1: Double, diagonal2: Double) {

        
        
        self.init(create_RhombusFigure(diagonal1, diagonal2), true)
    }
}