void:
  custom:
    is_c_pointer_type: False
  types:
    swift: Void
    c: void
    sc: Void
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

bool:
  custom:
    is_c_pointer_type: False
  types:
    swift: Bool
    c: bool
    sc: CBool
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

int:
  custom:
    is_c_pointer_type: False
  types:
    swift: Int
    c: int
    sc: CInt
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
      let {{target_name}} = CInt({{name}})
    sc_to_swift:
      let {{target_name}} = Int({{name}})

unsigned int:
  custom:
    is_c_pointer_type: False
  types:
    swift: UInt
    c: unsigned int
    sc: CUnsignedInt
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
      let {{target_name}} = CUnsignedInt({{name}})
    sc_to_swift:
      let {{target_name}} = UInt({{name}})

short:
  custom:
    is_c_pointer_type: False
  types:
    swift: Short
    c: short
    sc: CShort
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

long:
  custom:
    is_c_pointer_type: False
  types:
    swift: CLong
    c: long
    sc: CLong
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

long long:
  custom:
    is_c_pointer_type: False
  types:
    swift: CLongLong
    c: long long
    sc: ClongLong
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

unsigned long:
  custom:
    is_c_pointer_type: False
  types:
    swift: CUnsignedLong
    c: unsigned long
    sc: CUnsignedLong
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

float:
  custom:
    is_c_pointer_type: False
  types:
    swift: Float
    c: float
    sc: CFloat
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:

double:
  custom:
    is_c_pointer_type: False
  types:
    swift: Double
    c: double
    sc: CDouble
  converters:
    c_to_cxx:
    cxx_to_c:
    swift_to_sc:
    sc_to_swift:
