nlohmann::json:
  swift:
    type_info: JsonObject
  c:
    type_info: String
  c_to_cxx: 
  cxx_to_c: 
  swift_to_c:
  c_to_swift: 


std::pair:
  swift:
    type_info: "Pair<{{args_t[0]}}, {{args_t[1]}}>"
  c:
    type_info: "Pair<{{args_t[0]}}, {{args_t[1]}}>"
  c_to_cxx: 
  cxx_to_c: 
  swift_to_c:
  c_to_swift: 
