/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 07/29/2021-14:29.
 * Please do not change it manually.
 */

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>

#include "cxx/containers/vector.hpp"

namespace py = pybind11;

void bindIegenExampleVectorItem(py::module& m) {
    using namespace iegen::example;
    py::class_<iegen::example::VectorItem> vectoritem(m, "VectorItem");

    vectoritem.def_readwrite("value", &iegen::example::VectorItem::value);

    vectoritem.def(py::init<int>(), py::arg("_value"));
}
void bindIegenExampleVectorExamples(py::module& m) {
    using namespace iegen::example;
    py::class_<iegen::example::VectorExamples> vectorexamples(m, "VectorExamples");

    vectorexamples.def(py::init<>());
    vectorexamples.def("add_int_vector", &iegen::example::VectorExamples::addIntVector, py::arg("v"));
    vectorexamples.def("add_obj_vector", &iegen::example::VectorExamples::addObjVector, py::arg("v"));
    vectorexamples.def("add_string_vector", &iegen::example::VectorExamples::addStringVector, py::arg("v"));
    vectorexamples.def("get_string_vector", &iegen::example::VectorExamples::getStringVector);
    vectorexamples.def("get_obj_vector", &iegen::example::VectorExamples::getObjVector);
    vectorexamples.def("get_int_vector", &iegen::example::VectorExamples::getIntVector);
}