/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/06/2022-05:22.
 * Please do not change it manually.
 */

#include <cxxabi.h>
#include <memory>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>

#include "cxx/containers/vector.hpp"

namespace py = pybind11;

void bindExamplesLibContainersVectorPygen(py::module& m) {
    {
        using namespace cppbind::example;
        py::class_<cppbind::example::VectorItem> vectorItem(m, "VectorItem");
        vectorItem.def_readwrite("value", &cppbind::example::VectorItem::value, py::return_value_policy::reference_internal);

        vectorItem.def(py::init<int>(), py::arg("_value"));
        vectorItem.def("__repr__", [](const cppbind::example::VectorItem& self) -> std::string {
            int status;
            const char* name = typeid(self).name();
            std::unique_ptr<char[], std::function<void(char*)>> demangledSymbol(
                __cxxabiv1::__cxa_demangle(name, nullptr, nullptr, &status), free);
            const char * classname = "cppbind::example::VectorItem";
            if (status == 0) {
                classname = demangledSymbol.get();
            }
            char res[96];
            snprintf(res, sizeof(res), "<0x%08zx: %s>", reinterpret_cast<std::size_t>(&self), classname);
            return res;
        });  
    }
    {
        using namespace cppbind::example;
        py::class_<cppbind::example::VectorExamples> vectorExamples(m, "VectorExamples");
        
        vectorExamples.def(py::init<>());
        vectorExamples.def("add_int_vector", &cppbind::example::VectorExamples::addIntVector, py::arg("v"));
        vectorExamples.def("add_obj_vector", &cppbind::example::VectorExamples::addObjVector, py::arg("v"));
        vectorExamples.def("add_string_vector", &cppbind::example::VectorExamples::addStringVector, py::arg("v"));
        vectorExamples.def("get_string_vector", &cppbind::example::VectorExamples::getStringVector, py::return_value_policy::automatic);
        vectorExamples.def("get_obj_vector", &cppbind::example::VectorExamples::getObjVector, py::return_value_policy::reference);
        vectorExamples.def("get_int_vector", &cppbind::example::VectorExamples::getIntVector, py::return_value_policy::automatic);
        vectorExamples.def("__repr__", [](const cppbind::example::VectorExamples& self) -> std::string {
            int status;
            const char* name = typeid(self).name();
            std::unique_ptr<char[], std::function<void(char*)>> demangledSymbol(
                __cxxabiv1::__cxa_demangle(name, nullptr, nullptr, &status), free);
            const char * classname = "cppbind::example::VectorExamples";
            if (status == 0) {
                classname = demangledSymbol.get();
            }
            char res[96];
            snprintf(res, sizeof(res), "<0x%08zx: %s>", reinterpret_cast<std::size_t>(&self), classname);
            return res;
        });  
    }
} /* bindExamplesLibContainersVectorPygen */
