/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 03/14/2022-13:56.
 * Please do not change it manually.
 */

#ifndef _C_yaml_example_WRAPPER_
#define _C_yaml_example_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_IegenExample_WithExternalAPIComments(IEGenCObject cself, bool owner);

    IEGenCObject create_IegenExample_WithExternalAPIComments(char* _Nonnull s, IEGenCObject* _Nonnull err);
    int _func_IegenExample_WithExternalAPIComments_retInt(int  n, IEGenCObject* _Nonnull err);
    char* _Nonnull _prop_get_IegenExample_WithExternalAPIComments_str(IEGenCObject cself, IEGenCObject* _Nonnull err);

    void _prop_set_IegenExample_WithExternalAPIComments_str(IEGenCObject cself, char* _Nonnull s, IEGenCObject* _Nonnull err);

    int _func_IegenExample_WithExternalAPIComments_maxInt(int  a, int  b, IEGenCObject* _Nonnull err);
    char* _Nonnull _func_IegenExample_WithExternalAPIComments_maxString(char* _Nonnull a, char* _Nonnull b, IEGenCObject* _Nonnull err);
    void release_IegenExample_AdderInt(IEGenCObject cself, bool owner);
    int _func_IegenExample_AdderInt_add(int  a, int  b, IEGenCObject* _Nonnull err);
    void release_IegenExample_AdderDouble(IEGenCObject cself, bool owner);
    double _func_IegenExample_AdderDouble_add(double  a, double  b, IEGenCObject* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_yaml_example_WRAPPER_ */
