cc_library(
    name = "examples_cc_library",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob([
        "**/*.hpp",
        "**/*.h",
    ]),
    visibility = ["//visibility:public"],
)

py_library(
    name = "examples_py_library",
    srcs = glob(["**/*.py"]),
    visibility = ["//visibility:public"],
)
