"""
  ______ .______   .______   .______    __  .__   __.  _______  
 /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
|  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
|  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
|  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 

This file is generated by cppbind on 06/03/2022-07:13.
Please do not change it manually.
"""
from __future__ import annotations

from typing import *

import examples.simple.holder as pybind_holder_pygen
import examples_lib.simple.task.task_pygen as task_task_pygen
from examples_lib.cppbind.bind_utils_pygen import *
from examples_lib.cppbind.metaclass_pygen import *


class Holder(metaclass=CppBindMetaclass):
    """
    Documentation generated from: `cxx/simple/holder.hpp#L13
    <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/simple/holder.hpp#L13>`_
    """
    
    @bind
    def __init__(self):
        """
        Documentation generated from: `cxx/simple/holder.hpp#L21
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/simple/holder.hpp#L21>`_
        """
        pass
    
    @property
    @bind
    def task(self) -> task_task_pygen.PyTask:
        """
        Documentation generated from: `cxx/simple/holder.hpp#L28
        <https://github.com/PicsArt/cppbind/tree/master/examples/primitives/cxx/simple/holder.hpp#L28>`_
        """
        pass

    @bind
    def __repr__(self) -> str:
        """
        CPPBind generated __repr__ method returning underlying C++ object type and id.
        """
        pass
