- file:
    files_glob: 
      - "{{[vars.helpers_dir, '**/*.py'] | path_join}}"
    copy_to: |
      {%- set file_rel_name = path.relpath(file_name, vars.helpers_dir) -%}
      {{path.join(path.join(vars.out_dir, vars.helpers_package_prefix.replace('.', pat_sep)), file_rel_name)}}

    variables:
      helper_includes: |
        {%- set file_rel_name = path.relpath(file_name, vars.helpers_dir) -%}
        {{vars.helpers_include_prefix}}{{'.' if vars.helpers_include_prefix}}{{path.splitext(file_rel_name)[0].replace(pat_sep, '.')}}

- file:
    files_glob:
      - "{{[vars.cxx_base_dir, '**/*.h*'] | path_join}}"
      - "{{[vars.cxx_base_dir, '**/*.c*'] | path_join}}"
    copy_to: |
      {%- if vars.cxx_base_out_dir is defined -%}
      {%- set file_rel_name = path.relpath(file_name, vars.cxx_base_dir) -%}
      {{path.join(vars.cxx_base_out_dir, file_rel_name)}}
      {%- endif -%}
