void:
  types:
    python: None
    pybind: None
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind:

bool:
  types:
    python: bool
    pybind: bool
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})

int:
  types:
    python: int
    pybind: int
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})

unsigned int:
  long

short:
  types:
    python: int
    pybind: int
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})

long:
  types:
    python: int
    pybind: int
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})

long long:
  long

unsigned long:
  long

float:
  types:
    python: float
    pybind: float
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})

double:
  types:
    python: float
    pybind: float
  converters:
    cxx_to_pybind:
    pybind_to_cxx:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})
