#void:
#  python:
#    type_info: None
#  pybind:
#    type_info: None
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
#bool:
#  python:
#    type_info: bool
#  pybind:
#    type_info: bool
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
#int:
#  python:
#    type_info: int
#  pybind:
#    type_info: int
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
#unsigned int:
#  long
#
#short:
#  python:
#    type_info: short
#  pybind:
#    type_info: short
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
#
#long:
#  python:
#    type_info: long
#  pybind:
#    type_info: long
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
#long long:
#  long
#
#unsigned long:
#  long
#
#float:
#  python:
#    type_info: double
#  pybind:
#    type_info: double
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
#double:
#  python:
#    type_info: double
#  pybind:
#    type_info: double
#  cxx_to_pybind:
#  pybind_to_cxx:
#  pybind_to_python:
#  python_to_pybind:
#
