void:
  custom:
    pname: None
    tname: None
  python:
    type_info: None
  pybind:
    type_info: None
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind:

bool:
  custom:
    pname: bool
    tname: Bool
  python:
    type_info: bool
  pybind:
    type_info: bool
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})

int:
  custom:
    pname: int
    tname: Int
  python:
    type_info: int
  pybind:
    type_info: int
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})

unsigned int:
  long

short:
  custom:
    pname: int
    tname: Int
  python:
    type_info: int
  pybind:
    type_info: int
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})

long:
  custom:
    pname: int
    tname: Int
  python:
    type_info: int
  pybind:
    type_info: int
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})

long long:
  long

unsigned long:
  long

float:
  custom:
    pname: float
    tname: Float
  python:
    type_info: float
  pybind:
    type_info: float
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})

double:
  custom:
    pname: float
    tname: Float
  python:
    type_info: float
  pybind:
    type_info: float
  cxx_to_pybind:
  pybind_to_cxx:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})
