file:
  python_init:
    file_path: |
      {{config.out_dir + pat_sep + [config.package_prefix, package, '__init__']|map('replace', '.', pat_sep)|path_join}}.{{config.extension}}
    scopes:
      - include
      - code_fragment
    content: |
      {{helper.python.make_comment((banner_logo + '\n' + banner_comment).split('\n'))}}
      {{include}}
      {%- if code_fragment %}
      {{code_fragment}}
      {%- else %}
      {{''}}
      {%- endif %}
  python:
    file_path: |
      {{config.out_dir + pat_sep + [config.package_prefix, package, file + config.file_postfix]|map('replace', '.', pat_sep)|path_join}}.{{config.extension}}
    scopes:
      - body
      - include
    content: |
      {{helper.python.make_comment((banner_logo + '\n' + banner_comment).split('\n'))}}

      from __future__ import annotations

      from typing import *

      import {{[config.pybind_module, package, file]|join('.')}} as {{'pybind_' + file + config.file_postfix}}
      from bind_utils import *
      {{helper_includes|format_list('from {} import *')|join('\n')}}
      {%- if include %}
      {{include}}
      {%- endif %}
      {{body}}
      {{''}}
  cxx:
    file_path: |
      {{cxx_output_filepath}}.cpp
    scopes:
      - body
      - include
    content: |
      {{helper.make_doxygen_comment((banner_logo + '\n' + banner_comment).split('\n'))}}

      #include <pybind11/pybind11.h>
      #include <pybind11/stl.h>
      #include <pybind11/functional.h>

      {{include}}

      namespace py = pybind11;

      {{body|string}}
  hpp:
    file_path: |
      {{cxx_output_filepath}}.hpp
    scopes:
      - body
    content: |
      {{helper.make_doxygen_comment((banner_logo + '\n' + banner_comment).split('\n'))}}

      {% set filename = [package, file]|map('replace', '.', '_')|join('_') -%}
      #ifndef {{filename}}_hpp
      #define {{filename}}_hpp

      #include <pybind11/pybind11.h>

      namespace py = pybind11;

      {{body|string}}

      #endif
  pybind_module_cxx:
    file_path: |
      {{config.cxx_out_dir + pat_sep + [config.package_prefix, config.pybind_module.split('.')[-1] + config.file_postfix]|map('replace', '.', pat_sep)|path_join}}.cpp
    scopes:
      - body
    content: |
      {{helper.make_doxygen_comment((banner_logo + '\n' + banner_comment).split('\n'))}}

      #include <pybind11/pybind11.h>
      #include "{{config.pybind_module.split('.')[-1] + config.file_postfix}}.hpp"

      namespace py = pybind11;
      void bind{{config.pybind_module.replace('.', '_')|capitalize|to_camel_case}}(py::module& m) {
          {{body|string|indent}}
      }
  pybind_module_hpp:
    file_path: |
      {{config.cxx_out_dir + pat_sep + [config.package_prefix, config.pybind_module.split('.')[-1] + config.file_postfix]|map('replace', '.', pat_sep)|path_join}}.hpp
    scopes:
      - include
    content: |
      {{helper.make_doxygen_comment((banner_logo + '\n' + banner_comment).split('\n'))}}

      {% set package = config.pybind_module.split('.')[-1] -%}
      #ifndef {{package + config.file_postfix}}_hpp
      #define {{package + config.file_postfix}}_hpp

      {{include}}
      #include <pybind11/pybind11.h>

      namespace py = pybind11;
      void bind{{config.pybind_module.replace('.', '_')|capitalize|to_camel_case}}(py::module& m);

      #endif
  pybind_package:
    file_path: |
      {{config.cxx_out_dir + pat_sep + [config.pybind_module.split('.')[-1] + '_module']|map('replace', '.', pat_sep)|path_join}}.cpp
    gen: false
    scopes:
      - body
    content: |
      {{helper.make_doxygen_comment((banner_logo + '\n' + banner_comment).split('\n'))}}
      {% set packages = config.pybind_module.split('.') %}
      {%- set package = packages[0] %}
      {%- set file = config.cxx_out_dir +pat_sep + [config.package_prefix, config.pybind_module.split('.')[-1] + config.file_postfix]|map('replace', '.', pat_sep)|path_join %}
      #include <pybind11/pybind11.h>
      #include "{{helper.python.cxx_rel_path(file, config.out_prj_dir)}}.hpp"

      namespace py = pybind11;
      PYBIND11_MODULE({{package}}, m) {
          py::module_ parent = m;
          {%- for p in packages[1:] %}
          {%- set parent_module = packages[loop.index - 1] %}
          py::module_ {{parent_module}} = parent.def_submodule("{{p}}", "{{p}}");
          parent = {{parent_module}};
          {%- endfor %}
          bind{{helper.python.module_name_to_func_name(config.pybind_module)}}(parent);
      }

  bind: !include bind_snippet.yaml

var_pybind_module_cxx: &var_pybind_module
  body:
    unique_content: |
      {%- set package_name = package|replace('.', '_') -%}
      {{marker}}py::module_ {{package_name}} = m.def_submodule("{{package}}", "{{package}}");
      {{marker}}py::module_ {{package_name}}_{{file}} = {{package_name}}.def_submodule("{{file}}", "{{file}}");
      {{marker}}bind{{name}}{{template_suffix if ctx.kind_name != 'enum'}}({{package_name}}_{{file}});

package:
  python_init:
    code_fragment:
      unique_content: |
        {%- if code_fragment -%}
        {{marker}}
        {{code_fragment|join('\n\n\n')}}
        {%- endif -%}
    include:
      unique_content: |
        {{include|format_list('from {} import *')|join_unique}}

var_pybind_module_hpp: &var_pybind_module_hpp
  include:
    unique_content: |
      {{marker}}#include "{{helper.python.cxx_rel_path(cxx_output_filepath + '.hpp', config.out_prj_dir)}}"

enum:
  python:
    body: |
      {% set m = 'pybind_' + file + config['file_postfix'] %}

      class {{name}}({{m}}.{{name}}):
          {{comment|string|indent}}
          {%- for case in enum_cases -%}
          {%- if case.comment %}
          {{case.comment|string|indent(4)}}
          {%- endif %}
          {{case.name}} = {{m}}.{{name}}.{{case.name}}
          {%- endfor %}
  python_init:
    include:
      unique_content: |
        from .{{file + config.file_postfix}} import {{name}}
  cxx:
    body: |
      void {{'bind' + name}}(py::module& m) {
          py::enum_<{{cxx_type_name}}>(m, "{{name}}")
              {%- for case in enum_cases %}
              .value("{{case.name}}", {{cxx_type_name}}::{{case.name}})
              {%- endfor %}
              .export_values();
      }
    include:
      unique_content: |
        #include "{{prj_rel_file_name}}"
  hpp:
    body: |
      void {{'bind' + name}}(py::module& m);
  pybind_module_cxx: *var_pybind_module
  pybind_module_hpp: *var_pybind_module_hpp
  pybind_package:
    body:

var_class: &var_class
  python:
    include:
      unique_content: |
        {%- if is_abstract -%}
        {{marker}}from abc import abstractmethod
        {%- endif -%}
        {%- if include -%}
        {{include|format_list("from {} import *")|join_unique}}
        {%- endif -%}
    body:
      scopes:
        - constructor_body
        - properties
        - body
      content: |
        {% set comma = joiner(', ')  %}

        class {{name}}{{template_suffix}}({%- if base_types_converters is defined -%}
                                  {% for base_type_converter in base_types_converters -%}
                                  {{comma()}}{{base_type_converter.python.target_type_name}}
                                  {%- endfor -%}
                                  {%- endif -%}
                       {{comma()}}metaclass=OriginalMethodsMetaclass):
            {%- if comment %}
            {{comment|string|indent}}
            {%- endif %}
            {%- if not is_abstract %}
            {%- if constructor_body %}
            {{constructor_body|string|indent}}
            {%- endif %}
            {%- else %}
            @abstractmethod
            def __init__(self, *args, **kwargs):
                pass
            {%- endif %}
            {%- if properties %}
            {{properties|string|indent}}
            {%- endif %}
            {%- if body %}
            {{body|string|indent}}
            {%- endif %}
  python_init:
    include:
      unique_content: |
        from .{{file + config.file_postfix}} import {{name}}{{template_suffix}}
  cxx:
    include:
      unique_content: |
        #include "{{prj_rel_file_name}}"
        {%- set template_includes = ctx.template_includes -%}
        {%- if template_includes -%}
        {{marker}}{{template_includes|format_list('#include "{}"')|join_unique}}
        {%- endif -%}
        {%- set decl_includes = helper.python.get_declaration_includes(ctx, config)|format_list('#include "{}"')|join_unique -%}
        {%- if decl_includes -%}
        {{marker}}{{decl_includes}}
        {%- endif -%}
        {%- if include_cxx -%}
        {{marker}}{{include_cxx|format_list('#include "{}"')|join_unique}}
        {%- endif -%}
    body:
      scopes:
        - body
      content: |
        void {{'bind' + name + template_suffix}}(py::module& m) {
            {%- if ctx.namespace %}
            using namespace {{ctx.namespace}};
            {%- endif %}
            {% set comma = joiner(', ') -%}
            {% set shared_ptr = 'std::shared_ptr<' + cxx_type_name + '>' -%}
            py::class_<{{cxx_type_name}} {%- if shared_ref or ancestors|any('shared_ref') -%}
                                          , std::shared_ptr<{{cxx_type_name}}>
                                         {%- endif %}
                                         {%- if base_types_converters is defined -%},
                                         {%- for base_type in base_types_converters -%}
                                         {{comma()}}{{base_type.python.cxx_type_name}}
                                         {%- endfor -%}
                                         {%- endif %}> {{name|lower}}{{template_suffix|capitalize}}(m, "{{name}}{{template_suffix}}"{{', py::is_final()' if not is_open}});
        {{body|string|indent}}
        }
  hpp:
    body: |
      void {{'bind' + name + template_suffix}}(py::module& m);
  pybind_module_cxx: *var_pybind_module
  pybind_module_hpp: *var_pybind_module_hpp
  pybind_package:
    body:

class: *var_class

interface: *var_class

var_template_method_include: &var_template_method_include
    unique_content: |
      {%- set template_includes = ctx.template_includes|format_list('#include "{}"')|join_unique -%}
      {%- if template_includes -%}
      {{template_includes}}
      {%- endif %}

var_bind_method: &var_bind_method
  converter:
    unique_content: |
      {%- for arg in args -%}
      {%- set converter = arg.converter.python_to_pybind -%}
      {%- set snippet = converter.snippet('arg') -%}
      {%- if snippet -%}
      {{marker}}elif type_hint == '{{arg.converter.python.target_type_name}}':
          {{snippet|indent}}
          return {{converter.converted_name('arg')}}
      {%- endif -%}
      {%- endfor -%}

constructor:
  python:
    constructor_body: |
      {% set comma = joiner(', ') %}
      @bind
      def __init__(self{{', ' if args}}{%- for arg in args -%}
                                       {{comma()}}{{arg.name|to_snake_case}}: {{arg.converter.python.target_type_name}}{{helper.python.get_default_value(arg)}}
                                       {%- endfor %}):
          {{comment|string|to_snake_case(args|map(attribute='name'))|indent}}
          pass
  bind: *var_bind_method
  cxx:
    body: |
      {%- set comma = joiner(', ') %}
      {{owner_class.name|lower}}{{owner_class.template_suffix|capitalize}}.def(py::init<{%- for arg in args -%}
                                                                                   {{comma()}}{{arg.converter.python.cxx_type_name}}
                                                                                   {%- endfor -%}>(){{', ' if args}}{{args|format_list('py::arg("{arg.name}")', 'arg')|join(', ')|to_snake_case}});

    include: *var_template_method_include

function:
  python:
    body: |
      {%- set comma = joiner(', ') -%}
      {%- if is_static %}
      @classmethod
      {%- endif %}
      {%- if is_operator %}
      {%- set _name = helper.python.get_operator_name(name) %}
      {%- else %}
      {%- set _name = name|to_snake_case %}
      {%- endif %}
      @bind
      def {{_name}}({{'self' if not is_static else 'cls'}}{{', ' if args}}
                                                          {%- for arg in args -%}
                                                          {{comma()}}{{arg.name|to_snake_case}}: {{arg.converter.python.target_type_name}}{{helper.python.get_default_value(arg)}}
                                                          {%- endfor %}) -> {{rconverter.python.target_type_name}}:
          {{comment|string|to_snake_case(args|map(attribute='name'))|indent}}
          pass
  bind: *var_bind_method
  cxx:
    body: |
      {%- if is_operator %}
      {%- set _name = helper.python.get_operator_name(name) -%}
      {%- else -%}
      {%- set _name = name|to_snake_case -%}
      {%- endif %}
      {%- set comma = joiner(', ') -%}
      {{owner_class.name|lower}}{{owner_class.template_suffix|capitalize}}.def{{'_static' if is_static }}("{{_name}}"{%- if helper.python.is_overloaded_cursor(ctx) -%}
      , py::overload_cast<
      {%- for arg in args -%}
      {{comma()}}{%- if arg.converter.ctx -%}
      {{arg.converter.python.cxx_type_name}}
      {%- else -%}
      {{arg.type.spelling}}
      {%- endif -%}
      {%- endfor -%}>(&{{owner_class.cxx_type_name}}::{{cxx_name}}{{', py::const_' if ctx.cursor.is_const_method()}})
      {%- else -%}
      , &{{owner_class.cxx_type_name}}::{{cxx_name}}
      {%- endif -%}
      {%- if ctx.node.is_function_template -%}
      <{{template_choice.values()|format_list("{type}", 'type')|join(', ')}}>
      {%- endif -%}
      {{', ' if args}}{{args|format_list('py::arg("{arg.name}")', 'arg')|join(', ')|to_snake_case}});
    include: *var_template_method_include

var_bind_getter: &var_bind_getter
  converter:
    unique_content: |
      {%- set converter = rconverter.python_to_pybind -%}
      {%- set snippet = converter.snippet('arg') -%}
      {%- if snippet -%}
      {{marker}}elif type_hint == '{{rconverter.python.target_type_name}}':
          {{snippet|indent}}
          return {{converter.converted_name('arg')}}
      {%- endif -%}

property_getter:
  python:
    properties: |
      {% set _name = name|to_snake_case %}
      @property
      @bind
      def {{_name}}(self) -> {{rconverter.python.target_type_name}}:
          {{comment|string|indent}}
          pass
      {% if gen_property_setter %}
      @{{_name}}.setter
      @bind
      def {{_name}}(self, value: {{rconverter.python.target_type_name}}):
          {{comment|string|indent}}
          pass
      {%- endif %}
  bind: *var_bind_getter
  cxx:
    body: |
      {%- set _name = name|to_snake_case -%}
      {%- if gen_property_setter %}
      {{owner_class.name|lower}}{{owner_class.template_suffix|capitalize}}.def_readwrite("{{_name}}", &{{owner_class.cxx_type_name}}::{{cxx_name}});
      {%- else %}
      {{owner_class.name|lower}}{{owner_class.template_suffix|capitalize}}.def_readonly("{{_name}}", &{{owner_class.cxx_type_name}}::{{cxx_name}});
      {%- endif %}

getter:
  python:
    properties: |
      {%- if ctx.node.is_function_template %}
      {%- set _name = overloading_prefix|to_snake_case %}
      {%- if template_names %}
      {%- set _name = template_names|join|to_snake_case %}
      {%- endif %}
      {%- else %}
      {%- set _name = name|to_snake_case %}
      {%- endif %}
      @property
      @bind
      def {{_name}}(self) -> {{rconverter.python.target_type_name}}:
          {{comment|string|indent}}
          pass
      {%- if setter_ctx is defined %}

      @{{_name}}{{overloading_prefix if ctx.node.is_function_template}}.setter
      @bind
      def {{_name}}{{overloading_prefix if ctx.node.is_function_template}}(self, value: {{rconverter.python.target_type_name}}):
          {{comment|string|indent}}
          pass
      {%- endif -%}
  bind: *var_bind_getter
  cxx:
    body: |
      {%- if ctx.node.is_function_template %}
      {%- set _name = overloading_prefix|to_snake_case  %}
      {%- if template_names %}
      {%- set _name = template_names|join|to_snake_case %}
      {% endif %}
      {%- else %}
      {%- set _name = name|to_snake_case %}
      {%- endif %}
      {% if setter_ctx is defined %}
      {{owner_class.name|lower}}{{owner_class.template_suffix|capitalize}}.def_property("{{_name}}", &{{owner_class.cxx_type_name}}::{{cxx_name}}, &{{owner_class.cxx_type_name}}::{{setter_ctx.cxx_name}});
      {%- else %}
      {{owner_class.name|lower}}{{owner_class.template_suffix|capitalize}}.def_property_readonly("{{_name}}", &{{owner_class.cxx_type_name}}::{{cxx_name}}{%- if ctx.node.is_function_template -%}
                                                                                                                                                          <{{template_choice.values()|format_list("{type}", 'type')|join(', ')}}>
                                                                                                                                                          {%- endif %});
      {%- endif %}
