char:
  std::__cxx11::basic_string

std::string:
  std::__cxx11::basic_string

std::__ndk1::shared_ptr:
  std::shared_ptr

std::__ndk1::vector:
  std::vector

std::__ndk1::map:
  std::map

std::__ndk1::unordered_map:
  std::map

std::__ndk1::function:
  std::function

std::__ndk1::basic_string:
  std::__cxx11::basic_string

std::__ndk1::pair:
  std::pair

std::__1::shared_ptr:
  std::shared_ptr

std::__1::vector:
  std::vector

std::__1::map:
  std::map

std::__1::unordered_map:
  std::map

std::__1::function:
  std::function

std::__1::basic_string:
  std::__cxx11::basic_string

std::__1::pair:
  std::pair

$Object:
  custom:
    pname: object
  types:
    python: "{{type_name}}{{template_suffix}}"
    pybind: "{{type_name}}{{template_suffix}}"
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

$Enum:
  custom:
    pname: int
  types:
    python: "{{type_name}}"
    pybind: "{{type_name}}"
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

$FunctionProto:
  custom:
    pname: int
  types:
    python: |
      {%- set comma = joiner(', ') -%}Callable[[{%- for arg in args_t[:-1] -%}{{comma()}}{{arg}}{%- endfor -%}], {{args_t|last}}]
    pybind: |
        {%- set comma = joiner(', ') -%}Callable[[{%- for arg in args_t[:-1] -%}{{comma()}}{{arg}}{%- endfor -%}], {{args_t|last}}]
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

std::__cxx11::basic_string:
  custom:
    pname: str
  types:
    python: str
    pybind: str
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    pybind_to_python:
    python_to_pybind: |
      {{target_name}} = {{target_type_name}}({{name}})

std::string_view:
  std::__cxx11::basic_string

std::vector:
  custom:
    pname: list
  types:
    python: List[{{args_t[0]}}]
    pybind: list
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

std::function:
  custom:
    pname: function
  types:
    python: "{{args_t[0]}}"
    pybind: "{{args_t[0]}}"
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

std::map:
  custom:
    pname: dict
  types:
    python: dict
    pybind: dict
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

std::unordered_map:
  std::map

std::shared_ptr:
  custom:
    pname: object
  types:
    python: "{{args_t[0]}}"
    pybind: "{{args_t[0]}}"
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

nlohmann::json:
  custom:
    pname: json
  types:
    python: dict
    pybind: dict
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:

json:
  nlohmann::json

std::pair:
  custom:
    pname: tuple
  types:
    python: tuple
    pybind: tuple
  converters:
    pybind_to_cxx:
    cxx_to_pybind:
    python_to_pybind:
    pybind_to_python:
