char:
  std::__cxx11::basic_string

std::string:
  std::__cxx11::basic_string

std::__ndk1::shared_ptr:
  std::shared_ptr

std::__ndk1::vector:
  std::vector

std::__ndk1::map:
  std::map

std::__ndk1::unordered_map:
  std::map

std::__ndk1::function:
  std::function

std::__ndk1::basic_string:
  std::__cxx11::basic_string

$Object:
  custom:
    pname: object
  python:
    type_info: "{{type_name}}{{template_suffix}}"
  pybind:
    type_info: "{{type_name}}{{template_suffix}}"
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

$Enum:
  custom:
    pname: int
  python:
    type_info: "{{type_name}}"
  pybind:
    type_info: "{{type_name}}"
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

$FunctionProto:
  custom:
    pname: int
  python:
    type_info: |
      {%- set comma = joiner(', ') -%}Callable[[{%- for arg in args_t[:-1] -%}{{comma()}}{{arg}}{%- endfor -%}], {{args_t|last}}]
  pybind:
    type_info: |
      {%- set comma = joiner(', ') -%}Callable[[{%- for arg in args_t[:-1] -%}{{comma()}}{{arg}}{%- endfor -%}], {{args_t|last}}]
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

std::__cxx11::basic_string:
  custom:
    pname: str
  python:
    type_info: str
  pybind:
    type_info: str
  pybind_to_cxx:
  cxx_to_pybind:
  pybind_to_python:
  python_to_pybind: |
    {{target_name}} = {{target_type_name}}({{name}})


std::vector:
  custom:
    pname: list
  python:
    type_info: List[{{args_t[0]}}]
  pybind:
    type_info: list
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

std::function:
  custom:
    pname: function
  python:
    type_info: "{{args_t[0]}}"
  pybind:
    type_info: "{{args_t[0]}}"
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

std::map:
  custom:
    pname: dict
  python:
    type_info: dict
  pybind:
    type_info: dict
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

std::unordered_map:
  std::map


std::shared_ptr:
  custom:
    pname: object
  python:
    type_info: "{{args_t[0]}}"
  pybind:
    type_info: "{{args_t[0]}}"
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:


std::__ndk1::pair:
  std::pair

nlohmann::json:
  custom:
    pname: json
  python:
    type_info: dict
  pybind:
    type_info: dict
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python:

json:
  nlohmann::json

std::pair:
  custom:
    pname: tuple
  python:
    type_info: tuple
  pybind:
    type_info: tuple
  pybind_to_cxx:
  cxx_to_pybind:
  python_to_pybind:
  pybind_to_python: