std::__ndk1::pair:
  std::pair

nlohmann::json:
  custom:
    pname: json
  python:
    type_info: dict
  pybind:
    type_info: dict


json:
  nlohmann::json

std::pair:
  custom:
    pname: tuple
  python:
    type_info: tuple
  pybind:
    type_info: tuple