#nlohmann::json:
#  custom:
#    pname: json
#  kotlin:
#    type_info: JsonObject
#  jni:
#    type_info: jstring
#  jdk:
#    type_info: String
#  jni_to_cxx: |
#    auto {{target_name}} = json::parse(iegen::jni_to_string(env, {{name}}))
#  cxx_to_jni: |
#    {{target_type_name}} {{target_name}} = iegen::string_to_jni(env, {{name}}.dump(4));
#  kotlin_to_jdk:
#    val {{target_name}} = {{name}}.toString()
#  jdk_to_kotlin: |
#    val {{target_name}}: {{target_type_name}} = JsonParser.parseString({{name}}).asJsonObject()