/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/09/2022-13:05.
 * Please do not change it manually.
 */

#ifndef _SWIFT_WRAPPERS_GETTERS_C_SWIFT_NUMBER_H_
#define _SWIFT_WRAPPERS_GETTERS_C_SWIFT_NUMBER_H_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_CppbindExample_NumberInt(CppBindCObject cself, bool owner);

    CppBindCObject create_CppbindExample_NumberInt(int n, CppBindCObject* _Nonnull cppbind_err);
    int _func_CppbindExample_NumberInt_toInt(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    int _prop_get_CppbindExample_NumberInt_num(CppBindCObject cself);
    void _prop_set_CppbindExample_NumberInt_num(CppBindCObject cself, int num);

    void release_CppbindExample_NumberDouble(CppBindCObject cself, bool owner);

    CppBindCObject create_CppbindExample_NumberDouble(double n, CppBindCObject* _Nonnull cppbind_err);
    int _func_CppbindExample_NumberDouble_toInt(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    double _prop_get_CppbindExample_NumberDouble_num(CppBindCObject cself);
    void _prop_set_CppbindExample_NumberDouble_num(CppBindCObject cself, double num);

#if __cplusplus
}
#endif
#endif /* ifndef _SWIFT_WRAPPERS_GETTERS_C_SWIFT_NUMBER_H_ */
