/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 12/06/2021-14:37.
 * Please do not change it manually.
 */

#ifndef _C_shared_ptr_WRAPPER_
#define _C_shared_ptr_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_Car(CObject cself);

    CObject create_Car(int cost, ErrorObj* _Nonnull err);
    int _prop_get_Car_cost(CObject cself);
    void _func_Car_setCostWithCarSharedPtr(CObject cself, CObject  sp, ErrorObj* _Nonnull err);
    void _func_Car_setCostWithCar(CObject cself, CObject  sp, ErrorObj* _Nonnull err);
    void _func_Car_setCostWithCarConstSharedPtr(CObject cself, CObject  sp, ErrorObj* _Nonnull err);
    CObject _func_Car_makeConstSharedPtr(CObject cself, CObject  sp, ErrorObj* _Nonnull err);
    void _func_Car_setCostWithCarRef(CObject cself, CObject  sp, ErrorObj* _Nonnull err);
    void _func_Car_setCostWithCarPtr(CObject cself, CObject  sp, ErrorObj* _Nonnull err);
    CObject _func_Car_getNewCarSharedPtr(CObject cself, ErrorObj* _Nonnull err);
    void release_CarUsage(CObject cself);

    CObject create_CarUsage(CObject car, ErrorObj* _Nonnull err);
    CObject _func_CarUsage_getCar(CObject cself, ErrorObj* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_shared_ptr_WRAPPER_ */