/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 02/22/2022-13:23.
 * Please do not change it manually.
 */

#ifndef _C_counter_WRAPPER_
#define _C_counter_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_Counter(IEGenCObject cself, bool owner);

    IEGenCObject create_Counter(int count, IEGenCObject* _Nonnull err);
    int _prop_get_Counter_count(IEGenCObject cself, IEGenCObject* _Nonnull err);
    IEGenCObject _func_Counter__add_(IEGenCObject cself, IEGenCObject  counter, IEGenCObject* _Nonnull err);
    bool _func_Counter__gt_(IEGenCObject cself, IEGenCObject  counter, IEGenCObject* _Nonnull err);
    IEGenCObject _func_Counter__iadd_(IEGenCObject cself, IEGenCObject  counter, IEGenCObject* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_counter_WRAPPER_ */
