"""
,--.,------. ,----.   ,------.,--.  ,--. 
|  ||  .---''  .-.|   |  .---'|  ,'.|  | 
|  ||  `--, |  | .---.|  `--, |  |' '  | 
|  ||  `---.'  '--'  ||  `---.|  | `   | 
`--'`------' `------' `------'`--'  `--' 

This file is generated by iegen on 07/09/2021-13:52.
Please do not change it manually.
"""

from __future__ import annotations

from typing import *

import examples.optionals.optionals as pybind_optionals_pygen
from bind_utils import *
from metaclass import *
import simple.task.task_pygen as task
import enums.color_pygen as color


class Optionals(metaclass=OriginalMethodsMetaclass):
    """
    Documentation generated from: `cxx/optionals/optionals.hpp#L17
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L17>`_
    """
    
    @bind
    def __init__(self):
        """
        constructor
        Documentation generated from: `cxx/optionals/optionals.hpp#L26
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L26>`_
        """
        pass
    
    @bind
    def optional_ptr_with_nullptr_default(self, task: Optional[task.PyTask] = None) -> Optional[task.PyTask]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L35
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L35>`_
        """
        pass

    @bind
    def optional_int_with_default(self, val: int = 5) -> int:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L44
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L44>`_
        """
        pass

    @bind
    def optional_string_with_default(self, optional_str: str = "abc") -> str:
        """
        @param[in] optional_str string with default value
        Documentation generated from: `cxx/optionals/optionals.hpp#L54
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L54>`_
        """
        pass

    @bind
    def optional_char_with_default(self, symbol: str = ',') -> str:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L63
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L63>`_
        """
        pass

    @bind
    def optional_ptr_with_null_default(self, task: Optional[task.PyTask] = None) -> Optional[task.PyTask]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L73
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L73>`_
        """
        pass

    @bind
    def optional_enum_with_default(self, c: color.Color = color.Color.Red) -> color.Color:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L82
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L82>`_
        """
        pass
