"""
,--.,------. ,----.   ,------.,--.  ,--. 
|  ||  .---''  .-.|   |  .---'|  ,'.|  | 
|  ||  `--, |  | .---.|  `--, |  |' '  | 
|  ||  `---.'  '--'  ||  `---.|  | `   | 
`--'`------' `------' `------'`--'  `--' 

This file is generated by iegen on 07/02/2021-09:03.
Please do not change it manually.
"""

from __future__ import annotations

from typing import *

import examples.optionals.optionals as pybind_optionals_pygen
from bind_utils import *
from metaclass import *
import simple.task.task_pygen as task
import enums.color_pygen as color


class Optionals(metaclass=OriginalMethodsMetaclass):
    """
    Documentation generated from: `cxx/optionals/optionals.hpp#L18
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L18>`_
    """
    
    @bind
    def __init__(self):
        """
        constructor
        Documentation generated from: `cxx/optionals/optionals.hpp#L27
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L27>`_
        """
        pass
    
    @bind
    def optional_ptr_with_nullptr_default(self, task: Optional[task.PyTask] = None) -> Optional[task.PyTask]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L36
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L36>`_
        """
        pass

    @bind
    def optional_int_with_default(self, val: int = 5) -> int:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L45
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L45>`_
        """
        pass

    @bind
    def optional_string_with_default(self, optional_str: str = "abc") -> str:
        """
        @param[in] optional_str string with default value
        Documentation generated from: `cxx/optionals/optionals.hpp#L55
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L55>`_
        """
        pass

    @bind
    def optional_char_with_default(self, symbol: str = ',') -> str:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L64
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L64>`_
        """
        pass

    @bind
    def optional_ptr_with_null_default(self, task: Optional[task.PyTask] = None) -> Optional[task.PyTask]:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L74
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L74>`_
        """
        pass

    @bind
    def optional_enum_with_default(self, c: color.Color = color.Color.Red) -> color.Color:
        """
        Documentation generated from: `cxx/optionals/optionals.hpp#L83
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/optionals/optionals.hpp#L83>`_
        """
        pass
