"""
,--.,------. ,----.   ,------.,--.  ,--. 
|  ||  .---''  .-.|   |  .---'|  ,'.|  | 
|  ||  `--, |  | .---.|  `--, |  |' '  | 
|  ||  `---.'  '--'  ||  `---.|  | `   | 
`--'`------' `------' `------'`--'  `--' 

This file is generated by iegen on 11/03/2021-12:27.
Please do not change it manually.
"""
from __future__ import annotations

from typing import *

import examples.shared_ptr.shared_ptr as pybind_shared_ptr_pygen
from examples_lib.iegen.bind_utils import *
from examples_lib.iegen.metaclass import *


class Car(metaclass=OriginalMethodsMetaclass):
    """
    Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L13
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L13>`_
    """
    
    @bind
    def __init__(self, cost: int):
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L19
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L19>`_
        """
        pass
    
    @property
    @bind
    def cost(self) -> int:
        """
        value getter
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L31
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L31>`_
        """
        pass
    
    @bind
    def set_cost_with_car_shared_ptr(self, sp: Car) -> None:
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L40
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L40>`_
        """
        pass

    @bind
    def set_cost_with_car(self, sp: Car) -> None:
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L49
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L49>`_
        """
        pass

    @bind
    def set_cost_with_car_ref(self, sp: Car) -> None:
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L58
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L58>`_
        """
        pass

    @bind
    def set_cost_with_car_ptr(self, sp: Car) -> None:
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L67
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L67>`_
        """
        pass

    @bind
    def get_new_car_shared_ptr(self) -> Car:
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L76
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L76>`_
        """
        pass


class CarUsage(metaclass=OriginalMethodsMetaclass):
    """
    Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L91
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L91>`_
    """
    
    @bind
    def __init__(self, car: Car):
        """
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L97
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L97>`_
        """
        pass
    
    @bind
    def get_car(self) -> Car:
        """
        Iegen supports only by value return in case shared_ref is set
        Documentation generated from: `cxx/shared_ptr/shared_ptr.hpp#L105
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/shared_ptr/shared_ptr.hpp#L105>`_
        """
        pass
