/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 09/02/2021-07:34.
 * Please do not change it manually.
 */

#include "jni.h"
#include <iostream>
#include "kotlin/wrappers/iegen_wrapper_helper.hpp"
#include "cxx/shared_ptr/shared_ptr.hpp"

using namespace Example;


extern "C" JNIEXPORT void Java_com_examples_shared_1ptr_Car_jFinalize(JNIEnv* env, jobject obj, jobjectid id){
    
    auto jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<Example::Car>*>(id);
    delete jni_to_cxx_id.get();
}
extern "C" JNIEXPORT jobjectid Java_com_examples_shared_1ptr_Car_jConstructor(JNIEnv* env, jobject obj, jint cost){
    
    Example::Car* obj_ptr = new Example::Car(cost);
    auto this_object = std::shared_ptr<Example::Car>(obj_ptr);
    return reinterpret_cast<jlong>(new std::shared_ptr<Example::Car>(this_object));
}

extern "C" JNIEXPORT jint Java_com_examples_shared_1ptr_Car_jCost(JNIEnv* env, jobject obj, jobjectid id){
    validateID(id);
    
    auto jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<Example::Car>*>(id);
    try {
        auto result = jni_to_cxx_id->cost();
        
        return result;
    }
    
    catch (const std::exception& e) {
        jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
        jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
        env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF(e.what()));
    }
    catch (...) {
        jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
        jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
        env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF("Uncaught Exception"));
    }

    jint result;
    return result;
}


extern "C" JNIEXPORT void Java_com_examples_shared_1ptr_Car_jSetcostwithcarsharedptr(JNIEnv* env, jobject obj, jobjectid id, jobjectid sp){
    

    std::shared_ptr<Example::Car> jni_to_cxx_sp;
    jni_to_cxx_sp = *reinterpret_cast<std::shared_ptr<Example::Car>*>(sp);

    validateID(id);
    auto jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<Example::Car>*>(id);
    
    try {
        jni_to_cxx_id->setCostWithCarSharedPtr(jni_to_cxx_sp);
        return;
    }
    catch (const std::exception& e) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF(e.what()));
    }
    catch (...) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF("Uncaught Exception"));
    }


}


extern "C" JNIEXPORT jobjectid Java_com_examples_shared_1ptr_Car_jGetnewcarsharedptr(JNIEnv* env, jobject obj, jobjectid id){
    
    validateID(id);
    auto jni_to_cxx_id = *reinterpret_cast<std::shared_ptr<Example::Car>*>(id);
    
    try {
        auto result = jni_to_cxx_id->getNewCarSharedPtr();
        
        jobjectid cxx_to_jni_result;
        cxx_to_jni_result = reinterpret_cast<jlong>(new std::shared_ptr<Example::Car>(result));
        return cxx_to_jni_result;
    }
    catch (const std::exception& e) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF(e.what()));
    }
    catch (...) {
          jclass handlerCls = env->FindClass("exceptionUtils/ExceptionHandler");
          jmethodID handlerMethod = env->GetStaticMethodID(handlerCls, "handleUncaughtException", "(Ljava/lang/String;)V");
          env->CallStaticVoidMethod(handlerCls, handlerMethod, env->NewStringUTF("Uncaught Exception"));
    }

    jobjectid result;
    return result;
}