"""
,--.,------. ,----.   ,------.,--.  ,--. 
|  ||  .---''  .-.|   |  .---'|  ,'.|  | 
|  ||  `--, |  | .---.|  `--, |  |' '  | 
|  ||  `---.'  '--'  ||  `---.|  | `   | 
`--'`------' `------' `------'`--'  `--' 

This file is generated by iegen on 06/28/2021-12:54.
Please do not change it manually.
"""

from __future__ import annotations

from typing import *

import examples.forward_decl.teacher as pybind_teacher_pygen
from bind_utils import *
from metaclass import *
import forward_decl.student_pygen as student


class Teacher(metaclass=OriginalMethodsMetaclass):
    """
    comments

    Documentation generated from: `cxx/forward_decl/teacher.hpp#L27
    <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/forward_decl/teacher.hpp#L27>`_
    """
    
    @bind
    def __init__(self):
        """
        Documentation generated from: `cxx/forward_decl/teacher.hpp#L33
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/forward_decl/teacher.hpp#L33>`_
        """
        pass
    
    @bind
    def add_student(self, s: student.Student) -> None:
        """
        Documentation generated from: `cxx/forward_decl/teacher.hpp#L40
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/forward_decl/teacher.hpp#L40>`_
        """
        pass

    @bind
    def students(self) -> list:
        """
        Documentation generated from: `cxx/forward_decl/teacher.hpp#L49
        <https://github.com/PicsArt/iegen/tree/master/examples/primitives/cxx/forward_decl/teacher.hpp#L49>`_
        """
        pass
