/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 08/17/2021-06:50.
 * Please do not change it manually.
 */

#include <pybind11/pybind11.h>
#include "python/wrappers/hello_user/hello_user.hpp"

namespace py = pybind11;
PYBIND11_MODULE(hello_user, m) {
    py::module_ parent = m;
    bindHelloUser(parent);
}