/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 05/25/2022-14:38.
 * Please do not change it manually.
 */

#ifndef _SWIFT_WRAPPERS_INHERITANCE_C_BICYCLE_H_
#define _SWIFT_WRAPPERS_INHERITANCE_C_BICYCLE_H_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    
    CppBindCObject create_CppbindExample_Bicycle(int number_of_seats, CppBindCObject* _Nonnull cppbind_err);
    char* _Nonnull _func_CppbindExample_Bicycle_type(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
#if __cplusplus
}
#endif
#endif /* ifndef _SWIFT_WRAPPERS_INHERITANCE_C_BICYCLE_H_ */
