/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 03/07/2022-14:41.
 * Please do not change it manually.
 */

#ifndef _C_bicycle_WRAPPER_
#define _C_bicycle_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    
    IEGenCObject create_IegenExample_Bicycle(int numberOfSeats, IEGenCObject* _Nonnull err);
    char* _Nonnull _func_IegenExample_Bicycle_type(IEGenCObject cself, IEGenCObject* _Nonnull err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_bicycle_WRAPPER_ */
