/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 05/12/2022-10:26.
 * Please do not change it manually.
 */

#ifndef _C_datetime_WRAPPER_
#define _C_datetime_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_CppbindExample_TimeImpl(CppBindCObject cself, bool owner);

    CppBindCObject create_CppbindExample_Time(int h, int m, int s, CppBindCObject* _Nonnull cppbind_err);
    char* _Nonnull _func_CppbindExample_Time_value(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    char* _Nonnull _prop_get_CppbindExample_Time_time(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);

    CppBindCObject create_CppbindExample_DateTime(int d, int mo, int y, int h, int mi, int s, CppBindCObject* _Nonnull cppbind_err);
    char* _Nonnull _func_CppbindExample_DateTime_value(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
    char* _Nonnull _prop_get_CppbindExample_DateTime_datetime(CppBindCObject cself, CppBindCObject* _Nonnull cppbind_err);
#if __cplusplus
}
#endif
#endif /* ifndef _C_datetime_WRAPPER_ */
