/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 03/10/2022-14:09.
 * Please do not change it manually.
 */

#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <cxxabi.h>
#include <memory>
#include <type_traits>
#include "swift/wrappers/inheritance/c_rectangle.h"
#include "cxx/inheritance/rectangle.hpp"
#include "cxx/inheritance/parallelogram.hpp"
#include "cxx/inheritance/square.hpp"

using namespace iegen::example;

void release_IegenExample_RectangleImpl(IEGenCObject cself, bool owner) {
    static_assert(std::has_virtual_destructor<iegen::example::Rectangle>::value, "iegen::example::Rectangle type must have virtual destructor");
    free(cself.type);
    if (owner) {
        delete static_cast<iegen::example::Rectangle*>(cself.ptr);
    }
}

IEGenCObject create_IegenExample_Rectangle(double length, double width, IEGenCObject* _Nonnull err) {
    try {
        auto this_object = new iegen::example::Rectangle(length, width);
        return {strdup("iegen::example::Rectangle"), this_object};
    } catch (const std::exception& e) {
        err->type = strdup("std::exception");
        err->ptr = new std::exception(e);
    } catch (...) {
        err->type = strdup("Uncaught Exception");
    }
    IEGenCObject result {};
    return result;
}

double _prop_get_IegenExample_Rectangle_area(IEGenCObject cself, IEGenCObject* _Nonnull err) {iegen::example::Rectangle* ctocxxcself = nullptr;
    if (cself.ptr) {
        if (strcmp(cself.type, "iegen::example::Rectangle") == 0)
            ctocxxcself = static_cast<iegen::example::Rectangle*>(cself.ptr);
        else if (strcmp(cself.type, "iegen::example::Square") == 0)
            ctocxxcself = static_cast<iegen::example::Square*>(cself.ptr);
        else {
            std::cerr << "Unexpected object type: " << cself.type << std::endl;
            exit(1);
        }
    }
    try {
        const auto& result = ctocxxcself->area();
        
        return result;
    } catch (const std::exception& e) {
        err->type = strdup("std::exception");
        err->ptr = new std::exception(e);
    } catch (...) {
        err->type = strdup("Uncaught Exception");
    }
    double result {};
    return result;
}

double _prop_get_IegenExample_Rectangle_length(IEGenCObject cself, IEGenCObject* _Nonnull err) {iegen::example::Rectangle* ctocxxcself = nullptr;
    if (cself.ptr) {
        if (strcmp(cself.type, "iegen::example::Rectangle") == 0)
            ctocxxcself = static_cast<iegen::example::Rectangle*>(cself.ptr);
        else if (strcmp(cself.type, "iegen::example::Square") == 0)
            ctocxxcself = static_cast<iegen::example::Square*>(cself.ptr);
        else {
            std::cerr << "Unexpected object type: " << cself.type << std::endl;
            exit(1);
        }
    }
    try {
        const auto& result = ctocxxcself->length();
        
        return result;
    } catch (const std::exception& e) {
        err->type = strdup("std::exception");
        err->ptr = new std::exception(e);
    } catch (...) {
        err->type = strdup("Uncaught Exception");
    }
    double result {};
    return result;
}

double _prop_get_IegenExample_Rectangle_width(IEGenCObject cself, IEGenCObject* _Nonnull err) {iegen::example::Rectangle* ctocxxcself = nullptr;
    if (cself.ptr) {
        if (strcmp(cself.type, "iegen::example::Rectangle") == 0)
            ctocxxcself = static_cast<iegen::example::Rectangle*>(cself.ptr);
        else if (strcmp(cself.type, "iegen::example::Square") == 0)
            ctocxxcself = static_cast<iegen::example::Square*>(cself.ptr);
        else {
            std::cerr << "Unexpected object type: " << cself.type << std::endl;
            exit(1);
        }
    }
    try {
        const auto& result = ctocxxcself->width();
        
        return result;
    } catch (const std::exception& e) {
        err->type = strdup("std::exception");
        err->ptr = new std::exception(e);
    } catch (...) {
        err->type = strdup("Uncaught Exception");
    }
    double result {};
    return result;
}

