/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 02/03/2022-13:55.
 * Please do not change it manually.
 */

#ifndef _C_rectangle_WRAPPER_
#define _C_rectangle_WRAPPER_

#include "swift/wrappers/c_helpers.h"

#include <stdbool.h>

#if __cplusplus
extern "C" {
#endif
    void release_RectangleImpl(IEGenCObject cself, bool owner);

    IEGenCObject create_Rectangle(double length, double width, IEGenCObject* _Nonnull err);
    double _prop_get_Rectangle_area(IEGenCObject cself);
    double _prop_get_Rectangle_length(IEGenCObject cself);
    double _prop_get_Rectangle_width(IEGenCObject cself);
#if __cplusplus
}
#endif
#endif /* ifndef _C_rectangle_WRAPPER_ */
