/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 10/13/2021-14:38.
 * Please do not change it manually.
 */

#include <string.h>
#include <memory>
#include "swift/wrappers/inheritance/c_vehicle.h"
#include "cxx/inheritance/vehicle.hpp"

using namespace iegen::example;

void release_Vehicle(void* _Nonnull cself) {
    delete static_cast<std::shared_ptr<iegen::example::Vehicle>*>(cself);
}

int _prop_get_Vehicle_numberOfSeats(void* _Nonnull cself){
    std::shared_ptr<iegen::example::Vehicle> c_to_cxx_cself;
    c_to_cxx_cself = std::dynamic_pointer_cast<iegen::example::Vehicle>(*static_cast<std::shared_ptr<iegen::example::Vehicle>*>(cself));
    auto result = c_to_cxx_cself->numberOfSeats();
    
    return result;
}