/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 10/19/2021-14:49.
 * Please do not change it manually.
 */

import CWrapper
import Foundation
/**
 * Color Enum.
 */
public enum Color: CUnsignedInt, CustomStringConvertible {
    /**
     * Red = 1
     */
    case Red = 1
    /**
     * Green = 2
     */
    case Green = 2
    /**
     * Blue = 20
     */
    case Blue = 20

    public var description: String {
        return "\(self.rawValue)"
    }
}

public enum ColorShade: CUnsignedInt {
    /**
     * Light = 1
     */
    case ShadeLight = 1
    /**
     * Dark = 2
     */
    case ShadeDark = 2
}