/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 04/12/2022-06:07.
 * Please do not change it manually.
 */

#ifndef examples_lib_inheritance_car_pygen_hpp
#define examples_lib_inheritance_car_pygen_hpp

#include <pybind11/pybind11.h>

namespace py = pybind11;

void bindExamplesLibInheritanceCarPygen(py::module& m);

#endif
