/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 06/01/2022-07:50.
 * Please do not change it manually.
 */

#include <cxxabi.h>
#include <memory>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>

#include "cxx/inheritance/square.hpp"
#include "cxx/inheritance/rhombus.hpp"
#include "cxx/inheritance/rectangle.hpp"

namespace py = pybind11;

void bindExamplesLibInheritanceSquarePygen(py::module& m) {
    {
        using namespace cppbind::example;
        py::class_<cppbind::example::Square, cppbind::example::Rhombus, cppbind::example::Rectangle> square(m, "Square", py::is_final());
        
        square.def(py::init<double>(), py::arg("side"));

        square.def_property_readonly("area", &cppbind::example::Square::area, py::return_value_policy::reference_internal);
        square.def("perimeter", &cppbind::example::Square::perimeter, py::return_value_policy::automatic);  
    }
} /* bindExamplesLibInheritanceSquarePygen */
