# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
          python setup.py install
          brew install nlohmann-json
          # download android ndk
          curl -O https://dl.google.com/android/repository/android-ndk-r22-darwin-x86_64.zip
          unzip android-ndk-r22-darwin-x86_64.zip
          rm android-ndk-r22-darwin-x86_64.zip
          mv android-ndk-r22 /tmp/android-ndk
          # make a symbolic link to libclang to overcome SIP issue
          ln -s /Library/Developer/CommandLineTools/usr/lib/libclang.dylib  /usr/local/lib

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          pytest ./src/test/

      - name: Run comparison tests
        run: |
          bazel test //... --action_env=NDK_PATH=/tmp/android-ndk/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  --test_output=streamed

  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
          sudo apt-get install -y libclang-9-dev nlohmann-json3-dev
          python setup.py install

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests
        run: |
          pytest ./src/test/

      - name: Run comparison tests
        run: |
          bazel test //... --test_output=streamed
