name: docs-cleanup

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  delete-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }})" >> $GITHUB_ENV

      - name: Print deleted branch
        run: echo "${BRANCH_NAME}"

      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1.18.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IEGEN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IEGEN }}
          aws-region: us-east-1

      - name: Delete files from s3 amazon bucket with the AWS CLI
        run: aws s3 rm --recursive  s3://iegen.picsart.com/${BRANCH_NAME}/