name: CppBind documentation

on:
  push:
    branches: 
      - master

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  generate-docs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: cleanup-runs
    steps:   
      - uses: actions/checkout@v2.3.4
        name: Checkout branch
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.7'

      - name: Install python modules
        run: |
          python3 -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

      - name: Generate files
        run: make html
        working-directory: ./docs

      - name: remove buildinfo
        working-directory: ./docs
        run: rm -rf _build/html/.buildinfo || exit 0

      - name: Publish Cloudflare pages using wrangler
        run: npx wrangler pages publish html/ --project-name cppbind
        working-directory: ./docs/_build
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
