name: cppbind-publish
on:
  release:
    types: [published]

jobs:
  cppbind-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.9 python3.9-dev python3.9-venv
          python3.9 -m venv $HOME/venv-python3.9
          echo "VIRTUAL_ENV=$HOME/venv-python3.9" >> $GITHUB_ENV
          echo "$HOME/venv-python3.9/bin" >> $GITHUB_PATH
      
      - name: Add PYTHON_BIN_PATH to ENV
        run : echo "PYTHON_BIN_PATH=`which python3`" >> $GITHUB_ENV
        
      - name: Checkout branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive

      - name: Install requirements
        run : pip3 install -r src/requirements.txt

      - name: Set version name for release
#         if: github.event_name == 'release'
        shell: bash
        run: |
          VERSION_NAME=${GITHUB_REF##*/}
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          sed -i -r "s/version=\"[0-9]*\.[0-9]*\.[0-9]*\"/version=\"$VERSION_NAME\"/g" setup.py

      - name: Build
        run: python3 setup.py sdist bdist_wheel
        env:
          CC: clang

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PUBLISH_TOKEN }}
          verbose: true

      - name: Set env of the run url
        if: always()
        run: echo "RUN_URL=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_ENV

