name: Iegen documentation

on:
  push:
    branches: 
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  cleanup-runs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  generate-docs:
    if: github.event.pull_request.draft == false
    #runs-on: [self-hosted, linux]
    runs-on: ubuntu-latest
    needs: cleanup-runs
    steps:   
      - uses: actions/checkout@v2.3.4
        name: Checkout branch
        if: github.event_name == 'push'
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}

      - uses: actions/checkout@v2.3.4
        name: Checkout pull request
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1.18.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IEGEN }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IEGEN }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.7'

      - name: Install python modules
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx_rtd_theme==0.5.0
          python3 -m pip install sphinx==3.3.1
          python3 -m pip install sphinx-tabs==3.0.0

      - name: Generate files
        run: make html
        working-directory: ./docs

      - name: Push environment
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: PR environment
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'


      - name: Iegen deployment (rsync)
        run: aws s3 cp --recursive _build/html/ s3://iegen.picsart.com/${BRANCH_NAME}
        working-directory: ./docs

      - name: Publish docs url
        if: github.event_name == 'pull_request'
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: iegen_comment.md
